# -*- coding: utf-8 -*-
# Phase 1-3 data: Qatar, GCC, Middle East
# R(dict): c=company ct=type ti=title ot=otype co=country ci=city rm=remote pr=priority
# ta=tech_area tech=technologies ex=experience dg=degree du=duration
# sc=(training20, projects20, mentor10, conversion15, beginner10, company10, tech5, salary5, intl5)
# sa=salary vi=visa re=relocation po=posted dl=deadline st=status u=url so=source
# di=difficulty bs=beginner_suit ca=career_value le=learning_value cl=competition
# rq=requirements sk=skills_to_learn wy=why_good rk=risks rc=recommendation nt=notes il=intl rl=risk_level

ROWS = [

# ==================== QATAR (Priority 1) ====================
dict(c='Qatar Airways', ct='National airline / semi-government', ti='IT Graduate Development Programme', ot='Graduate Program', co='Qatar', ci='Doha', rm='On-site', pr=1,
 ta='Enterprise IT / Software Engineering', tech='Enterprise systems, IT rotations, Agile', ex='Fresh graduate (0 yrs)', dg='Bachelor (IT/CS/Engineering preferred)', du='Structured graduate track (multi-year, reported 5-year service commitment)',
 sc=(18,15,8,14,8,8,3,5,1), sa='Reported QAR 27,000-32,000/month for Qatari nationals (Grade 7, secondary source)', vi='No - Qatarization-focused (Qataris prioritized)', re='No', po='Not shown (careers portal)', dl='Rolling - check careers portal', st='Unverified - confirm on official portal',
 u='https://careers.qatarairways.com', so='Nucamp Qatar Tech Guide 2026 + Qatar Airways careers portal',
 di='Medium-Hard', bs='For Qataris: excellent. Non-Qataris: unlikely via this track', ca='Very high local employer brand; full aviation-IT rotations', le='High - structured curriculum + department rotations', cl='High (prestige employer, mostly Qatarization)',
 rq='Bachelor degree; Qatari nationality strongly preferred for graduate track; English fluency', sk='Data structures, SQL, one backend language, basic cloud',
 wy='Strongest structured employer-led career track in Qatar with reported high graduate pay and permanent employment', rk='Reported 5-year service commitment; openings not always visible; non-Qataris rarely admitted via this programme', rc='APPLY IF QATARI NATIONAL - HIGH PRIORITY', nt='Verify exact vacancy on the portal (search Graduate Development Programme). Salary figure is from a secondary source.', il='U', rl='Low'),

dict(c='Qatar Airways', ct='National airline / semi-government', ti='Summer Internship Programme', ot='Internship', co='Qatar', ci='Doha', rm='On-site', pr=1,
 ta='IT / Engineering / Business (multiple departments)', tech='Departmental rotations; exposure to airline tech & ops', ex='Student / fresh graduate (0 yrs)', dg='Enrolled Bachelor/Master student (recommendation letter needed)', du='~6-8 weeks (summer)',
 sc=(14,10,6,8,8,8,3,4,1), sa='Reported QAR 3,000-6,000/month (secondary source)', vi='No', re='No', po='Annual (2026 round closed 31 May 2026)', dl='Closed for 2026 - reopens ~Q1-Q2 2027', st='Closed (annual programme)',
 u='https://internshipshub.in/internships/qatar-airways-summer-internship-2026', so='InternshipsHub listing + Qatar Airways careers portal',
 di='Medium', bs='Yes - designed for students/fresh grads', ca='Prestige brand on CV; internal networking', le='Medium - rotations more than coding', cl='High',
 rq='University enrollment + recommendation letter; online assessments + interview', sk='English, fundamentals of CS, SQL basics',
 wy='Flagship national internship; strong CV signal inside Qatar market', rk='Not primarily a software-engineering internship; 2026 window closed', rc='GOOD TARGET FOR NEXT CYCLE (apply early 2027)', nt='2026 deadline was 31 May 2026 per listing.', il='U', rl='Low'),

dict(c='QCRI (HBKU - Qatar Foundation)', ct='Research institute (semi-government)', ti='Summer Internship Program 2026 (SIP)', ot='Internship (Research + Engineering)', co='Qatar', ci='Doha (Education City)', rm='On-site (2026 edition delivered via cohorts)', pr=1,
 ta='AI / Arabic NLP / Cybersecurity / Software Engineering', tech='Python, ML, NLP, security tooling, research engineering', ex='Student / early graduate', dg='Undergraduate or graduate student', du='8 weeks',
 sc=(16,14,9,6,7,9,5,3,1), sa='Stipend typically provided (confirm with institute)', vi='No', re='No', po='2026 window: 26 Mar - 10 Apr 2026', dl='Closed for 2026 (cohort ran May-Jul 2026) - expect window ~Mar-Apr 2027', st='Closed (annual programme)',
 u='https://www.hbku.edu.qa/en/academic-events/QCRI-SIP26', so='HBKU / QCRI official event page (verified 2026 cycle)',
 di='Medium', bs='Yes - built for students', ca='Top research brand in region; strong for AI/ML direction', le='Very high - real research + software development with QCRI scientists', cl='Medium-High',
 rq='Select 2 research areas; application form; competitive screening', sk='Python, ML fundamentals, Git, academic reading',
 wy='Genuine mentorship from scientists/engineers on real projects; best research-engineering entry point in Qatar', rk='Research-flavored (less enterprise product work); short 8 weeks; annual window', rc='HIGH PRIORITY FOR 2027 CYCLE - SET REMINDER MARCH 2027', nt='Applications were 26 Mar-10 Apr 2026; cohorts May-Jul 2026.', il='U', rl='Low'),

dict(c='Ooredoo Qatar', ct='Telecom (semi-government linked)', ti='Internship Opportunities (speculative pipeline) / Fresh Graduate tracks', ot='Internship / Trainee', co='Qatar', ci='Doha', rm='On-site', pr=1,
 ta='Telecom IT / Software / Networks', tech='Enterprise IT, integrations, telecom systems', ex='Student / fresh graduate', dg='Diploma or Bachelor', du='Varies (weeks-months)',
 sc=(12,8,5,7,8,7,3,2,1), sa='Not disclosed', vi='No', re='No', po='Open speculative portal (always-on pipeline)', dl='Rolling', st='Open (rolling pipeline) - Unverified for current cohort',
 u='https://ooredoo.sniperhire.net/qatar/vacancy/41240', so='Ooredoo official recruitment portal (sniperhire)',
 di='Easy-Medium', bs='Yes - speculative entry pipeline', ca='National telecom brand; telecom-to-software exposure', le='Medium - depends on assigned team', cl='Medium',
 rq='CV into pipeline; relevant discipline; English; Arabic a plus', sk='SQL, networking basics, Python',
 wy='Always-open official pipeline into Ooredoo internships and graduate roles', rk='Speculative: no guaranteed start date; older graduate-programme postings (2018) show conversion tracks exist but irregularly', rc='GOOD TARGET - submit CV and monitor portal', nt='A previous Fresh Graduate Developee Programme existed; new cycles appear irregularly on the portal.', il='U', rl='Low'),

dict(c='QNB Group (Qatar National Bank)', ct='Bank (semi-government)', ti='Internship Opportunities (locals) + Graduate Career Opportunities (Qatarization)', ot='Internship / Graduate Program', co='Qatar', ci='Doha', rm='On-site', pr=1,
 ta='Banking IT / Data / Cybersecurity', tech='Banking systems, data analytics, security tooling', ex='Fresh graduate / student', dg='Bachelor', du='Programme-based (months)',
 sc=(12,8,6,12,7,9,3,3,1), sa='Banking scale (not disclosed for programme)', vi='No', re='No', po='Vacancies posted 2026 (e.g., QNB2738 internship, QNB2667 graduate)', dl='Check portal per requisition', st='Unverified - listings seen via aggregator; apply via official QNB careers',
 u='https://www.gccrecruitments.com/qatar-national-bank-careers/', so='Aggregator listing of official QNB requisitions (QNB2738, QNB2667)',
 di='Medium', bs='Yes for internship track (locals); graduate track Qatarization-weighted', ca='Largest bank in MEA region - strong brand', le='Medium - banking tech exposure', cl='High',
 rq='Local applicants for internships; Qataris prioritized for graduate track', sk='SQL, Python, data analysis, banking-domain basics',
 wy='Structured graduate + internship requisitions at the largest regional bank', rk='Strong Qatarization preference; aggregator page is third-party - always apply via official QNB careers site', rc='HIGH PRIORITY IF QATARI / LOCAL - check official portal', nt='Official careers: qnb.com -> Careers. Requisition IDs from 2026 listings.', il='U', rl='Low'),

dict(c='QatarEnergy LNG', ct='Energy (state-owned)', ti='Fresh Qatari Graduate Opportunities - Computer Majors (National Graduate Development Program)', ot='Graduate Program', co='Qatar', ci='Doha / Ras Laffan', rm='On-site', pr=1,
 ta='IT / Computer Science (energy sector)', tech='Enterprise IT, OT/IT, data systems', ex='Fresh graduate (0 yrs)', dg='BSc Computer Science or Computer Engineering', du='Structured national graduate programme (competence-based, ~2 yrs)',
 sc=(17,12,8,15,9,8,3,5,1), sa='Top-tier GCC energy graduate package (tax-free; figures not published)', vi='No', re='No', po='2026 postings seen (Apr/Jun 2026, Req 14571)', dl='Check portal per requisition', st='Unverified - apply via official QatarEnergy LNG careers',
 u='https://gulfjobs.el7far.com/2026/06/qatarenergy-lng-qatar-careers-2026.html', so='Aggregator mirrors of official QatarEnergy LNG requisitions (Jun 2026)',
 di='Medium', bs='Yes - designed for fresh Qatari graduates', ca='Highest-paying structured graduate route in Qatar per market reports', le='High - formal competence framework + reviews', cl='High (Qatari nationals only)',
 rq='Qatari nationality; CS/CE degree; competence-based selection', sk='Programming fundamentals, databases, networking',
 wy='Elite national graduate programme for computer majors with near-guaranteed career path for Qataris', rk='Qatari nationals only; industrial-sector (not product software)', rc='APPLY NOW IF QATARI NATIONAL', nt='Requisition 14571 (Computer Majors) posted 2026; official portal: qatarenergy.qa careers.', il='U', rl='Low'),

dict(c='Snoonu', ct='Startup (Qatari super-app)', ti='Summer Internship 2026 - Talent Pool + Technology roles', ot='Internship / Junior roles', co='Qatar', ci='Lusail / Doha', rm='Hybrid/On-site', pr=1,
 ta='E-commerce platform engineering', tech='Mobile/web stack, logistics systems, CRM', ex='Student / fresh graduate', dg='Bachelor (any field for pool; tech roles prefer CS)', du='~2-3 months (May-Jul intake)',
 sc=(13,12,7,9,8,6,4,2,1), sa='Not disclosed for interns; junior dev salaries at Snoonu reported QAR 16,000-22,000 (secondary)', vi='No', re='No', po='Talent pool listing Oct 2025; selection Mar/Apr 2026', dl='Rolling via talent pool + active listings (e.g., CRM Internship, 2026)', st='Open (talent pool + some live roles) - Unverified',
 u='https://jobs.weekday.works/snoonu-talent-pool---summer-internship-2026', so='Snoonu talent-pool listing + Snoonu 2026 careers mirrors',
 di='Medium', bs='Yes - pool explicitly for students and fresh grads', ca="Qatar's fastest-growing homegrown tech company; real product work", le='High - fast-paced production environment, mentorship claimed', cl='Medium-High',
 rq='Full-time availability May-Jul; CV; tech roles need coding proof', sk='JavaScript or mobile stack, SQL, Git; product mindset',
 wy='Best Qatar startup for juniors per 2026 market reports; real business impact projects', rk='Startup pace; internship conversion not guaranteed; salary claims are secondary-source', rc='APPLY NOW - HIGH PRIORITY (Qatar residents)', nt='Also watch Snoonu LinkedIn for Junior Software Engineer roles.', il='U', rl='Low'),

dict(c='SkipCash', ct='Startup (Qatari fintech, Series A)', ti='Junior Developer / Engineering roles', ot='Junior Job', co='Qatar', ci='Doha', rm='On-site', pr=1,
 ta='Payments / Fintech engineering', tech='Merchant APIs, payment rails, web/mobile', ex='Junior (limited experience OK per market reports)', dg='CS/Engineering preferred', du='Permanent',
 sc=(8,14,6,8,7,5,4,3,1), sa='Not disclosed (fintech startup scale)', vi='No', re='No', po='2026 market reports (Series A Jan 2026)', dl='Check company careers/LinkedIn', st='Unverified - confirm current openings',
 u='https://www.nucamp.co/blog/top-10-tech-startups-hiring-junior-developers-in-qatar-in-2026', so='Nucamp Top-10 Qatar startups hiring juniors 2026',
 di='Medium', bs='Reported to hire juniors into lean teams', ca='Fintech + early responsibility on merchant API integrations', le='High - lean team, real payment features', cl='Medium',
 rq='Solid coding fundamentals; payments interest; Arabic/English', sk='One backend language, REST APIs, SQL, Git',
 wy='Qatar FinTech Hub alumnus with fresh funding actively building engineering team', rk='Small company risk; verify openings directly - blog is secondary source', rc='GOOD TARGET - contact directly via LinkedIn/website', nt='$4M Series A raised Jan 2026 (secondary source).', il='U', rl='Low'),

dict(c='CWallet', ct='Startup (Qatari fintech)', ti='Junior Developer / Engineering roles', ot='Junior Job', co='Qatar', ci='Doha', rm='On-site', pr=1,
 ta='Payments / Wallet app', tech='Mobile + backend, payment integrations', ex='Junior', dg='CS-related preferred', du='Permanent',
 sc=(8,13,6,8,7,5,4,3,1), sa='Not disclosed', vi='No', re='No', po='Not shown', dl='Check careers/LinkedIn', st='Unverified',
 u='https://www.nucamp.co/blog/coding-bootcamp-qatar-qat-inside-qatars-thriving-tech-hub-startups-and-success-stories', so='Nucamp Qatar tech-hub report (funded startups list)',
 di='Medium', bs='Possibly - small team', ca='Award-winning local fintech product experience', le='Medium-High', cl='Medium',
 rq='Coding portfolio; initiative', sk='Mobile or backend stack, APIs, Git',
 wy='Funded Qatari fintech (~$4M raised) building wallet products', rk='Openings unconfirmed; small-team hiring is ad-hoc', rc='GOOD TARGET - reach out directly', nt='Include GitHub portfolio in outreach.', il='U', rl='Low'),

dict(c='Dunetech Studios', ct='Startup (game studio, Doha)', ti='Unreal Engine Gameplay Programmer (entry level)', ot='Junior Job', co='Qatar', ci='Doha', rm='On-site', pr=1,
 ta='Game development', tech='Unreal Engine, C++, gameplay systems', ex='Entry level (posted as entry)', dg='Not required (portfolio-driven)', du='Permanent',
 sc=(6,12,4,5,8,3,3,2,1), sa='Not disclosed', vi='No', re='No', po='~21 days before Aug 2026 (Bayt)', dl='Check listing', st='Unverified - Easy Apply via Bayt',
 u='https://www.bayt.com/en/qatar/jobs/software-developer-intern-jobs/', so='Bayt.com listing (entry level, ~Aug 2026)',
 di='Medium', bs='Yes - posted entry level', ca='Real shipped game work in Qatar', le='Medium - C++/Unreal niche', cl='Low-Medium (niche)',
 rq='Unreal Engine portfolio; C++ basics', sk='C++, Unreal Engine, Git',
 wy='Rare entry-level software role posted openly in Qatar', rk='Small indie studio (stability); game-dev specialization', rc='APPLY IF REQUIREMENTS MET (have UE portfolio)', nt='Under Software Developer Intern search results; role is entry gameplay programmer.', il='U', rl='Low'),

dict(c='UrbaCon Trading & Contracting (UCC)', ct='Contracting group (in-house IT)', ti='Cloud Developer', ot='Junior/Mid Job', co='Qatar', ci='Doha', rm='On-site', pr=1,
 ta='Cloud engineering', tech='Cloud platforms, integrations, enterprise apps', ex='Some experience implied (works with senior architects)', dg='CS/Engineering', du='Permanent',
 sc=(5,10,4,5,4,5,4,2,1), sa='Not disclosed', vi='No', re='No', po='~13 days before Aug 2026 (Bayt)', dl='Check listing', st='Open (recent listing) - Unverified',
 u='https://www.bayt.com/en/qatar/jobs/internship-software-engineer-jobs/', so='Bayt.com listing (Aug 2026)',
 di='Medium', bs='Not clearly beginner - likely needs 1-2 yrs', ca='Local enterprise cloud exposure', le='Medium', cl='Medium',
 rq='Cloud fundamentals; able to partner with architects', sk='AWS/Azure basics, Python or C#, SQL',
 wy='Recent live Qatar listing in modern cloud area', rk='Requirement depth unclear; not a structured training role', rc='APPLY IF REQUIREMENTS MET', nt='Appeared under internship searches but description suggests mid-level.', il='U', rl='Low'),

dict(c='PwC Middle East', ct='Global consultancy (Big Four)', ti='COOP & Summer Internship Programme 2026 (incl. Doha office) / Middle East Graduate Programme', ot='Internship / Graduate Program', co='Qatar (plus KSA, UAE, Egypt, Jordan, Oman, Bahrain, Kuwait)', ci='Doha + others', rm='On-site/Hybrid', pr=1,
 ta='Technology consulting (tech & deals streams)', tech='Consulting tooling, data analysis, client delivery', ex='Student (final year) / fresh graduate', dg='Bachelor (STEM or business per stream); GPA 3.0+/4.0', du='COOP 4-6 months (Jan/Aug intakes); Summer 6-8 weeks (Jun-Aug)',
 sc=(12,10,7,10,7,9,3,3,2), sa='Paid (consulting intern scale, not published)', vi='Must be eligible to work in applying country (national/PR/student visa)', re='No', po='Programme pages posted Nov 2025 - Apr 2026', dl='2026 cycle intakes Jan/Aug; summer apps early 2026 (closed) - watch 2027 cycle', st='Annual - 2026 summer closed; COOP intakes recur',
 u='https://careers.pwc.com/job/Middle-East-TLS,-COOP-and-Summer-Internship-Programme-2026-Middle-East-Midd/1268228401/', so='PwC Middle East official careers page (verified live)',
 di='Medium-Hard', bs='Students yes; requires GPA 3.0+ and work eligibility in country', ca='Big-Four brand + client-project exposure across GCC', le='Medium - consulting process more than deep coding', cl='High',
 rq='Enrollment status, GPA, English; nationality/visa eligibility per office', sk='Excel/SQL, presentation, one programming language',
 wy='Multi-country GCC consultancy internship with Doha option and structured intakes', rk='Streams shown are tax/deals - tech consulting placement varies; conversion to full-time not guaranteed', rc='GOOD TARGET for client-facing consulting path (apply for 2027 cycle)', nt='Separate Watani graduate route exists for UAE nationals; ME Graduate Programme open via careers portal.', il='U', rl='Low'),

# ==================== SAUDI ARABIA (Priority 2) ====================
dict(c='Saudi Aramco', ct='Energy major (state-owned)', ti='Computing and IT Graduates (less than three years experience) - Req 1408', ot='Graduate Program / Entry-Level Job', co='Saudi Arabia', ci='Dhahran', rm='On-site', pr=2,
 ta='Enterprise IT / Software Engineering', tech='Business applications, systems, enterprise scale', ex='0-3 years (no prior work experience required)', dg='Bachelor+ in CS/SE/CE/IT/InfoSec (GPA >=2.0/4.0)', du='Permanent hire with development pathway',
 sc=(17,15,8,15,10,9,4,5,1), sa='Aramco premium package (housing/transport allowances; figures not published)', vi='No (Saudi nationals)', re='No', po='Opening 8 Oct 2025', dl='Closing 31 Dec 2026 - OPEN NOW', st='OPEN (verified on official Aramco careers)',
 u='https://careers.aramco.com/saudi/job/Computing-and-IT-Graduates-(less-than-three-years-of-work-experience)/766636523/', so='Aramco official careers site',
 di='Medium-Hard (selective but beginner-open)', bs='Yes - explicitly no prior experience required', ca='One of the best entry-level tech employers in the region', le='High - enterprise-scale systems + structured development', cl='High (many applicants, but designed for fresh grads)',
 rq='Saudi nationality; CS-family degree; GPA 2.0+/4.0; full-time study', sk='Programming fundamentals, databases, networking, English',
 wy='Official, verified, OPEN until end of 2026; entry-level by design at a top-tier employer', rk='Saudi nationals only; competitive screening', rc='APPLY NOW (Saudi nationals) - TOP CHOICE', nt='Job Req 1408; multiple computer majors accepted.', il='N', rl='Low'),

dict(c='stc (Saudi Telecom)', ct='Telecom (state-linked)', ti='Talent Incubation Program (TIP)', ot='Graduate Program', co='Saudi Arabia', ci='Riyadh', rm='On-site', pr=2,
 ta='Telecom / Digital services engineering', tech='Cutting-edge technologies and projects (per programme)', ex='< 1 year', dg='Bachelor/Master; GPA >=3.2/4.0; IELTS 5 / TOEFL 35', du='2 years, full-time contract from day one',
 sc=(17,13,9,14,8,8,4,5,1), sa='Full-time salary during programme (not published)', vi='No (Saudi nationals)', re='No', po='Programme page live (2026)', dl='Check careers portal for intake', st='Open (official programme page) - intake timing Unverified',
 u='https://careers.stc.com.sa/content/TIP/?locale=en_US', so='stc official careers site',
 di='Hard (GPA + English bar)', bs='Yes - fresh grads <1 yr experience', ca='Dedicated coach/mentor from industry SMEs; future-leader track', le='Very high - intensive development + business exposure', cl='High',
 rq='Saudi nationality; GPA 3.2+/4.0; IELTS 5+; <1 yr experience', sk='CS fundamentals, data, cloud basics',
 wy='Named mentor + full-time contract + structured 2-year development at the Kingdom telecom champion', rk='High GPA bar; Saudi nationals only', rc='APPLY NOW (Saudi nationals, GPA 3.2+)', nt='TIP = accelerated career development program with full-time job contract.', il='N', rl='Low'),

dict(c='SAMA (Saudi Central Bank)', ct='Central bank (government)', ti='SAMA Promising Professionals Program 2026 (SPP) - Business Technology track', ot='Graduate Program / Trainee', co='Saudi Arabia', ci='Riyadh', rm='On-site', pr=2,
 ta='Financial technology / Digital transformation / Data', tech='Operational tech, automation, data analysis, fintech, payments, cybersecurity awareness', ex='Recent graduates', dg='Bachelor/Master in IS, Cybersecurity, SE, IT, CS, Data Science, FinTech, AI (Saudi nationals)', du='Structured programme (rotations + classroom + coaching)',
 sc=(16,12,8,13,8,9,3,4,1), sa='Compensation package during programme (not published)', vi='No (Saudi nationals)', re='No', po='Posted 18 May 2026', dl='Check careers page', st='Open/Unverified - posted May 2026',
 u='https://careers.sama.gov.sa/job/Head-Office-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D8%AC-%D8%B3%D8%A7%D9%85%D8%A7-%D9%84%D9%84%D9%85%D9%87%D9%86%D9%8A%D9%8A%D9%86-%D8%A7%D9%84%D9%88%D8%A7%D8%B9%D8%AF%D9%8A%D9%86-2026-%28SPP%29/857221123/', so='SAMA official careers site (Arabic posting)',
 di='Hard (selective)', bs='Yes - targets new graduates', ca='Central-bank technology career track; very strong brand', le='High - rotations + certifications + coaching', cl='High',
 rq='Saudi nationality; very-good GPA+; strong English; assessment center + technical interview', sk='Data analysis, fundamentals of payments/fintech, SQL',
 wy='Flagship central-bank graduate programme with an explicit technology track', rk='Highly selective; Saudi nationals only', rc='APPLY NOW (Saudi nationals)', nt='5 tracks incl. Business Technology (IT).', il='N', rl='Low'),

dict(c='Tuwaiq Academy (SAFCSP)', ct='Government academy (Cybersecurity Federation)', ti='Software / AI / Full-Stack Bootcamps (free + stipend)', ot='Bootcamp-to-Employment', co='Saudi Arabia', ci='Riyadh (some online)', rm='Hybrid/On-site', pr=2,
 ta='Full-stack development, AI, cybersecurity, cloud', tech='Full-stack web, Agentic AI (2026), cloud, security', ex='Beginners + career changers accepted', dg='No strict degree bar for many bootcamps', du='Weeks to ~10-week intensive cycles (Q1/Q3 cycles)',
 sc=(16,10,7,12,9,7,4,4,1), sa='Reported monthly stipend SAR 3,000-4,000 during bootcamps (secondary)', vi='No (Saudi-focused; check each cohort)', re='No', po='2026 cycles announced (Feb 2026 AI bootcamps with NTDP)', dl='Per-cohort; cycles open Q1 and Q3', st='Open cycles - Unverified per cohort',
 u='https://en.sharikatmubasher.com/media-hub/news/21526406/tuwaiq-academy-opens-ai-product-building-bootcamps-for-2026', so='Sharikat Mubasher news + Nucamp Saudi guide (official academy: tuwaiq.edu.sa)',
 di='Medium', bs='Yes - accepts motivated learners regardless of degree', ca='Reported >80% junior placement; national ecosystem (NTDP incubation for top projects)', le='High - project-based, team bootcamp', cl='Medium-High',
 rq='Apply per cohort; assessments; commitment', sk='One language (Python/JS), Git, problem solving',
 wy='Free, stipended, government-backed bootcamps with hiring ecosystem behind them', rk='Placement rates are secondary-source claims; Saudi-priority cohorts', rc='HIGH PRIORITY (Saudi residents) - track next cohort', nt='NTDP partnership: top projects get incubation support up to SAR 1.5M.', il='U', rl='Low'),

dict(c='HRDF (Human Resources Development Fund)', ct='Government fund', ti='Cooperative Training Program (on-the-job training platform)', ot='Government Program / Trainee', co='Saudi Arabia', ci='Various', rm='On-site', pr=2,
 ta='IT / Engineering / Business co-op', tech='Depends on host employer', ex='Diploma/Bachelor students in co-op stage', dg='Diploma or Bachelor (student)', du='Co-op term (months), full-time on-site',
 sc=(12,10,5,9,8,6,3,2,1), sa='Training allowance via program rules', vi='No (Saudi system)', re='No', po='Platform live (2026)', dl='Rolling - apply to listed opportunities', st='Open (official platform)',
 u='https://www.hrdf.org.sa/en/products-and-services/programs/individuals/training/cooperative-training/', so='HRDF official site',
 di='Easy-Medium', bs='Yes - built for students entering workforce', ca='Official bridge into Saudi employers (incl. IT departments)', le='Medium - depends on host', cl='Medium',
 rq='Nafath registration; co-op requirement; Saudi labor-market rules', sk='Depends on target host; SQL/Python basics',
 wy='Government-run official channel to company co-op slots across Saudi employers', rk='Quality varies by host company', rc='GOOD TARGET (Saudi students) - register and filter IT', nt='Full-time, on-site only per program rules.', il='N', rl='Low'),

dict(c='Tabby', ct='Startup (GCC fintech unicorn)', ti='Intern Backend (Go) Engineer', ot='Internship', co='Saudi Arabia', ci='Riyadh', rm='On-site', pr=2,
 ta='Backend engineering (payments)', tech='Go, high-load backend systems, PostgreSQL, microservices', ex='Student or fresh grad; strong CS fundamentals', dg='CS/related (in progress or complete)', du='Full-time internship (months; Co-op/Tamheer-compatible)',
 sc=(13,18,8,12,7,6,5,3,1), sa='Self-funded (paid) internship by Tabby (amount not published)', vi='No (Saudi nationals only)', re='No', po='Live listings seen Aug-Sep 2026', dl='Check listing', st='OPEN (recent listings, Sep 2026)',
 u='https://www.bayt.com/en/saudi-arabia/jobs/tabby-jobs/', so='Tabby listings via Bayt/Glassdoor (Sep 2026)',
 di='Hard (technical bar)', bs='Open to fresh grads - but real engineering bar', ca='"Not educational by default - engineering role with real responsibility" (official wording)', le='Very high - production code from day one on core fintech systems', cl='High',
 rq='Go or strong OOP base; production-grade mindset; full-time engagement; Saudi nationals', sk='Go, PostgreSQL, REST APIs, Git, testing',
 wy='One of the few internships where juniors write production code for a unicorn fintech', rk='Expects full working-day pace; competitive; Saudi nationals only', rc='APPLY NOW (Saudi nationals, strong fundamentals)', nt='Official wording: interns contribute to core financial products serving millions.', il='N', rl='Low'),

dict(c='Tabby', ct='Startup (GCC fintech unicorn)', ti='AI Intern (real AI agents & automation)', ot='Internship', co='Saudi Arabia', ci='Riyadh', rm='On-site', pr=2,
 ta='AI engineering (applied)', tech='AI agents, automation, production workflows, Python', ex='Student or fresh grad', dg='CS/related', du='Internship (full-time pace)',
 sc=(12,16,8,12,6,6,5,3,1), sa='Paid by Tabby (not published)', vi='No (Saudi nationals)', re='No', po='Live listings seen Aug-Sep 2026', dl='Check listing', st='OPEN (recent listings, Sep 2026)',
 u='https://www.bayt.com/en/saudi-arabia/jobs/tabby-jobs/', so='Tabby listings via Bayt (Sep 2026)',
 di='Hard', bs='For strong juniors with AI interest', ca='Build/test/iterate AI solutions affecting production workflows', le='Very high - applied AI in fintech', cl='High',
 rq='Python; AI/LLM basics; ownership mindset', sk='Python, LLM APIs, automation, Git',
 wy='Applied-AI internship with real production impact at a leading fintech', rk='High bar; Saudi nationals only', rc='APPLY NOW if AI portfolio exists', nt='', il='N', rl='Low'),

dict(c='Tabby', ct='Startup (GCC fintech unicorn)', ti='DBA Intern (PostgreSQL)', ot='Internship', co='Saudi Arabia', ci='Riyadh', rm='On-site', pr=2,
 ta='Database engineering', tech='PostgreSQL, performance tuning, ops health', ex='Student or fresh grad', dg='CS/related', du='Internship',
 sc=(12,15,8,12,6,6,4,3,1), sa='Paid by Tabby (not published)', vi='No (Saudi nationals)', re='No', po='Live listings Aug-Sep 2026', dl='Check listing', st='OPEN (recent listing, Sep 2026)',
 u='https://www.bayt.com/en/saudi-arabia/jobs/tabby-jobs/', so='Tabby listings via Bayt (Sep 2026)',
 di='Hard', bs='Niche but junior-open', ca='Database engineering with senior engineers on critical production DBs', le='High - rare DBA exposure for juniors', cl='Medium-High',
 rq='SQL depth; curiosity for databases', sk='PostgreSQL, SQL tuning, Linux basics',
 wy='Junior database engineering seat inside a unicorn', rk='Specialist track; Saudi nationals only', rc='APPLY IF REQUIREMENTS MET', nt='', il='N', rl='Low'),

dict(c='Tamara / MRSOOL (Builders Program)', ct='Startup (KSA fintech unicorn / logistics)', ti='Builders Program - Associate ML Engineer / Associate Data Engineer (Co-op/Internship)', ot='Internship / Graduate Program', co='Saudi Arabia', ci='Riyadh', rm='On-site', pr=2,
 ta='ML / Data engineering', tech='Python, data pipelines, ML systems, cloud', ex='Fresh graduates (program for high-potential grads)', dg='Bachelor (CS/related)', du='Co-op/Internship cycle (months)',
 sc=(12,14,7,12,7,6,5,3,1), sa='Paid program (figures not published)', vi='No (Saudi-focused)', re='No', po='Listings active May 2026', dl='Check program page/listings', st='Open/Unverified - recent listings',
 u='https://www.bayt.com/en/saudi-arabia/jobs/tamara-jobs/', so='Tamara/MRSOOL listings via Bayt (May 2026)',
 di='Medium-Hard', bs='Designed for fresh grads (Builders Program)', ca="Saudi's first fintech unicorn program brand; rotations + mentoring by senior leaders", le='High - real ML/data production work', cl='High',
 rq='GPA + fundamentals; program assessments', sk='Python, SQL, data modeling, Git',
 wy='Named early-career program at a unicorn with clear talent-development intent', rk='Data/ML focus rather than classic SWE; conversion not guaranteed', rc='HIGH PRIORITY (Saudi fresh grads, data-oriented)', nt='MRSOOL Inc operates the Builders Program brand.', il='N', rl='Low'),

dict(c='InnovationTeam', ct='Startup (Riyadh, gov-tech consulting)', ti='Junior Developer', ot='Junior Job', co='Saudi Arabia', ci='Riyadh', rm='On-site', pr=2,
 ta='GovTech / cloud solutions', tech='Cloud architecture, compliance-driven apps', ex='Junior', dg='CS/Engineering', du='Permanent',
 sc=(9,13,6,8,8,5,4,2,1), sa='Not disclosed (market-rate junior SAR)', vi='No', re='No', po='2026 market report', dl='Check careers/LinkedIn', st='Unverified',
 u='https://www.nucamp.co/blog/top-10-tech-startups-hiring-junior-developers-in-saudi-arabia-in-2026', so='Nucamp Top-10 Saudi startups hiring juniors 2026',
 di='Medium', bs='Reported junior-friendly', ca='Gov-compliance + cloud experience valued by stc/Aramco later', le='Medium-High', cl='Medium',
 rq='Foundations; initiative', sk='Cloud basics, Python/Java, SQL',
 wy='Named among top Saudi startups actually hiring juniors in 2026', rk='Secondary-source listing; verify directly', rc='GOOD TARGET - verify opening on LinkedIn', nt='', il='U', rl='Low'),

dict(c='Lucidya', ct='Startup (Riyadh, AI/SaaS)', ti='Junior Developer (Go / Ruby on Rails)', ot='Junior Job', co='Saudi Arabia', ci='Riyadh', rm='On-site', pr=2,
 ta='AI-powered SaaS (customer experience)', tech='GoLang, Ruby on Rails', ex='Junior', dg='CS/related', du='Permanent',
 sc=(8,13,6,8,8,5,4,2,1), sa='Not disclosed', vi='No', re='No', po='2026 market report', dl='Check careers/LinkedIn', st='Unverified',
 u='https://www.nucamp.co/blog/top-10-tech-startups-hiring-junior-developers-in-saudi-arabia-in-2026', so='Nucamp Top-10 Saudi startups hiring juniors 2026',
 di='Medium', bs='Reported junior-friendly', ca='Rare Go/Rails production experience for juniors (scarcity value)', le='High - distinctive stack', cl='Medium',
 rq='Willingness to learn Go/Rails', sk='Go or Ruby, SQL, Git',
 wy='AI SaaS with enterprise clients; distinctive backend stack for CV differentiation', rk='Secondary source; niche stack', rc='GOOD TARGET if open to Go/Rails', nt='', il='U', rl='Low'),

# ==================== UAE (Priority 2) ====================
dict(c='Emirates NBD', ct='Bank', ti='Ruwad - UAE National Graduate Program (24 months)', ot='Graduate Program', co='UAE', ci='Dubai', rm='On-site', pr=2,
 ta='Banking technology (rotations possible in tech)', tech='Banking platforms, data, digital channels', ex='Fresh graduates (Emiratis)', dg='Bachelor/Master', du='24 months incl. 12-month secondment at partner org',
 sc=(15,10,8,13,7,8,3,4,1), sa='Very competitive salary & benefits (bank scale)', vi='No (UAE nationals only)', re='No', po='Programme page live', dl='Check careers portal', st='Open (official page) - intake Unverified',
 u='https://www.emiratesnbd.com/en/careers/join-emirates-nbd/graduates/ruwad', so='Emirates NBD official careers site',
 di='Hard (assessment center)', bs='Yes for fresh Emirati grads', ca='INSEAD/PwC training, exec networking, secondment', le='High - structured leadership+tech development', cl='High',
 rq='UAE nationality (Family Book); assessment center; interviews', sk='Data/SQL basics, banking-domain curiosity',
 wy='Flagship Emirati graduate leadership track with strong tech rotations', rk='UAE nationals only; leadership- not dev-focused', rc='APPLY NOW (UAE nationals)', nt='Bedaya + year-round Emirati internship also exist; non-nationals not eligible for these tracks.', il='N', rl='Low'),

dict(c='e& (Etisalat and)', ct='Telecom (state-linked)', ti='AI Graduate Programme', ot='Graduate Program', co='UAE', ci='Dubai/Abu Dhabi', rm='On-site', pr=2,
 ta='AI / Telecom tech', tech='AI, data, telecom platforms', ex='Fresh graduates', dg='Bachelor/Master (AI/CS/Engineering)', du='Graduate programme cycle',
 sc=(15,12,8,13,7,8,5,4,1), sa='Telecom graduate package (not published)', vi='UAE national programs exist alongside; international grad roles vary', re='No', po='Live listings 2026 (AI Graduate Programme)', dl='Check careers portal', st='Open/Unverified - live 2026 listing',
 u='https://www.gccrecruitments.com/etisalat-careers-dubai/', so='e& careers mirrors listing AI Graduate Programme (2026); official: e& careers',
 di='Medium-Hard', bs='Yes - graduate programme', ca='AI-focused graduate track at a major regional tech group', le='High - AI + telecom scale', cl='High',
 rq='AI/CS degree; assessments', sk='Python, ML basics, data handling',
 wy='One of few named AI graduate programmes in the GCC', rk='Aggregator source - confirm on official e& careers; nationality preferences vary by role', rc='HIGH PRIORITY - verify & apply on official portal', nt='Bidayati internship + NAFIS (UAE national) programmes also listed.', il='U', rl='Low'),

dict(c='e& (Etisalat and)', ct='Telecom (state-linked)', ti='Bidayati - Internship Programme', ot='Internship', co='UAE', ci='UAE offices', rm='On-site', pr=2,
 ta='Telecom IT (multiple teams)', tech='Telecom systems, digital services', ex='Students/fresh grads', dg='Enrolled or graduate', du='Internship term',
 sc=(12,8,6,8,8,8,4,2,1), sa='Internship allowance (not published)', vi='Eligibility per role (often UAE-based)', re='No', po='Listing active 2026 (posted Apr 2025, still listed)', dl='Rolling', st='Open/Unverified',
 u='https://www.gccrecruitments.com/etisalat-careers-dubai/', so='e& careers mirror (2026); official: e& careers',
 di='Medium', bs='Yes', ca='National telecom internship gateway', le='Medium', cl='Medium-High',
 rq='CV; eligibility in UAE', sk='Fundamentals + one language',
 wy='Structured official internship programme at a major telecom', rk='Conversion unclear', rc='GOOD TARGET (UAE-based applicants)', nt='', il='U', rl='Low'),

dict(c='First Abu Dhabi Bank (FAB)', ct='Bank', ti='Management Trainee Program 2025-2026 (tech majors included)', ot='Graduate Program', co='UAE', ci='Abu Dhabi', rm='On-site', pr=2,
 ta='Banking tech (Software Eng, Data, AI majors accepted)', tech='Data engineering/science, AI, cybersecurity tracks', ex='Graduated 2023-2026', dg='Bachelor; GPA >=3.7; UAE National with Family Book', du='Structured trainee programme + international secondments',
 sc=(14,8,8,13,7,8,3,4,1), sa='Bank trainee package', vi='No (UAE nationals)', re='International mobility possible', po='Listing active 2025-2026', dl='Check portal', st='Open/Unverified',
 u='https://www.bayt.com/en/uae/jobs/management-trainee-program-2025-2026-74456861/', so='Bayt listing of FAB programme (2025-2026)',
 di='Hard (GPA 3.7)', bs='For strong fresh grads', ca='Exec mentorship + secondments at largest UAE bank', le='Medium-High', cl='High',
 rq='UAE nationality + Family Book; GPA 3.7; tech/business majors', sk='SQL, data literacy, one language',
 wy='Elite bank trainee track explicitly accepting software engineering majors', rk='Very high GPA bar; Emiratis only', rc='APPLY NOW (UAE nationals, GPA 3.7+)', nt='', il='N', rl='Low'),

dict(c='42 Abu Dhabi (ADEK)', ct='Government coding school (tuition-free)', ti='Software Development program with built-in 6-month internship + Level 6 Diploma', ot='Academy/Training (with internship)', co='UAE', ci='Abu Dhabi', rm='On-site', pr=2,
 ta='Software development + AI applications', tech='C, C++, Python, web, peer projects (42 pedagogy)', ex='No experience required (18+, high-school certificate)', dg='No degree required - Level 6 qualification awarded', du='Common Core + specializations + 6-month internship',
 sc=(15,14,7,10,10,7,4,3,2), sa='Tuition-free; internship may be paid (varies)', vi='UAE residency needed to attend (check visa options)', re='No', po='Applications open year-round (Piscine selection cycles)', dl='Rolling - Piscine selection', st='Open (official FAQs verified)',
 u='https://42abudhabi.ae/faqs/', so='42 Abu Dhabi official site',
 di='Hard (intensive self-driven)', bs='Absolutely - zero coding experience needed', ca='NQC-accredited Level 6 (bachelor-equivalent) + mandatory internship; graduates often hired before completing', le='High - project-based, gamified, 24/7 campus', cl='Medium',
 rq='18+, high-school certificate, pass online game + Piscine', sk='C (starting), then C++/Python/web; peer collaboration',
 wy='Free elite coding school in the Gulf with an accredited diploma and a built-in internship step', rk='Demanding peer-learning model (no teachers); living costs in Abu Dhabi', rc='HIGH PRIORITY for beginners able to relocate/reside in UAE', nt='First GCC 42 network campus accredited at Level 6 by UAE NQC.', il='U', rl='Low'),

# ==================== OMAN / KUWAIT / BAHRAIN / JORDAN ====================
dict(c='Omantel', ct='Telecom (state-linked)', ti='Omantel Academy - digital talent program (12-month training + jobs)', ot='Trainee Program / Government-linked', co='Oman', ci='Muscat', rm='On-site', pr=2,
 ta='Digital technologies (Microsoft, Huawei, Cisco, Google, Oracle tracks)', tech='Vendor certifications + labs + real projects', ex='Omani graduates (bachelor, tech disciplines)', dg='Bachelor (technology-related)', du='12 months intensive per cohort (4-year learning journey; 500 jobs target)',
 sc=(16,10,8,14,9,7,4,4,1), sa='Training + employment pathway (allowances per program)', vi='No (Omanis)', re='No', po='Program launched Jan 2026 (1,200 training opportunities)', dl='Check Omantel Academy page for cohort intake', st='Open/Unverified - announced Jan 2026',
 u='https://www.zawya.com/en/press-release/events-and-conferences/omantel-academy-provides-1-200-training-opportunities-for-omani-youth-to-lead-the-future-of-digital-technologies-j9ujckzj', so='Zawya press release (Jan 2026)',
 di='Medium', bs='Yes - built for fresh Omani graduates', ca='1,200 seats + 500 job opportunities target = explicit training-to-employment', le='High - global vendor certifications + labs', cl='Medium',
 rq='Omani nationality; tech bachelor; cohort application', sk='Networking/cloud basics; pick a vendor track',
 wy='Large-scale, government-aligned training-to-jobs program with global certifications', rk='Omanis only; details of cohort timing need confirmation', rc='APPLY NOW (Omani nationals)', nt='4-year journey, 12-month intensive training per cohort.', il='N', rl='Low'),

dict(c='Zain Kuwait', ct='Telecom', ti='Graduate Apprenticeship (technology track)', ot='Apprenticeship', co='Kuwait', ci='Kuwait City', rm='On-site', pr=2,
 ta='Telecom tech (Big Data, AI tools, cybersecurity, Dizlee open API)', tech='SCRUM/Agile + hands-on projects', ex='Fresh graduates (Kuwaiti focus)', dg='Bachelor', du='12 months, salaried',
 sc=(14,10,8,12,8,7,4,5,1), sa='Reported KWD 1,000-1,300/month (secondary)', vi='No (Kuwaitization-oriented)', re='No', po='Annual window Oct-Dec for Feb cohort (secondary)', dl='Apply Oct-Dec 2026 for Feb 2027 cohort', st='Unverified - confirm with Zain careers',
 u='https://www.nucamp.co/blog/coding-bootcamp-kuwait-kwt-top-10-tech-internships-offered-in-kuwait', so='Nucamp Kuwait apprenticeships guide 2026',
 di='Medium', bs='Yes - apprenticeship by design', ca='Reported ~80%+ return-offer rate; exec networking + Agile training', le='High - salaried 12-month applied training', cl='Medium-High',
 rq='Kuwaiti national preferred; cohort window timing', sk='Data/AI basics, Agile, SQL',
 wy='Paid 12-month tech apprenticeship at a leading regional operator', rk='Window months away; salary/placement figures are secondary-source', rc='HIGH PRIORITY (Kuwaitis) - prepare for Oct-Dec 2026 window', nt='', il='N', rl='Low'),

dict(c='NBK (National Bank of Kuwait)', ct='Bank', ti='NBK Tech Academy', ot='Trainee Program', co='Kuwait', ci='Kuwait City', rm='On-site', pr=2,
 ta='Banking tech (RPA, digital banking, data office)', tech='RPA, digital transformation, data analytics', ex='Up to 4 years experience; fresh grads eligible', dg='Bachelor in MIS/InfoSec/DS/CS/Engineering (Kuwaiti grads)', du='Academy cohort (months) with department rotations',
 sc=(14,8,7,12,8,8,3,4,1), sa='Bank trainee package', vi='No (Kuwaitis)', re='No', po='Cohort 2 welcomed Feb 2025; further cohorts likely', dl='Watch NBK careers', st='Unverified for current cohort',
 u='https://www.gccbusinessnews.com/2nd-cohort-of-nbk-tech-academy/', so='GCC Business News on NBK Tech Academy cohort 2',
 di='Medium', bs='Yes - graduate academy', ca='Rotations incl. Digital Office, Weyay Bank, Data Office', le='High - real banking-tech rotations', cl='High',
 rq='Kuwaiti nationality; strong GPA; relevant majors', sk='SQL, RPA basics, data analysis',
 wy='Dedicated TECH academy (not generic banking) inside a leading Gulf bank', rk='Cohort timing irregular; Kuwaitis only', rc='GOOD TARGET (Kuwaitis) - monitor NBK careers', nt='', il='N', rl='Low'),

dict(c='Kuwait Finance House', ct='Bank (Islamic)', ti='Graduate track - Digital Transformation & IT rotations', ot='Graduate Program', co='Kuwait', ci='Kuwait City', rm='On-site', pr=2,
 ta='Digital banking / IT', tech='Digital banking stack', ex='Fresh graduates', dg='Bachelor', du='6-12 months salaried track',
 sc=(13,8,7,11,8,7,3,4,1), sa='Reported KWD 800-1,100/month (secondary)', vi='No (Kuwaitis)', re='No', po='Rolling, aligned to graduation cycles (secondary)', dl='Rolling', st='Unverified',
 u='https://www.nucamp.co/blog/coding-bootcamp-kuwait-kwt-top-10-tech-internships-offered-in-kuwait', so='Nucamp Kuwait guide 2026',
 di='Medium', bs='Yes', ca='Full-stack-of-bank exposure incl. digital transformation dept', le='Medium-High', cl='Medium',
 rq='Kuwaiti nationality; June-grad alignment', sk='SQL, data basics',
 wy='Salaried graduate track with explicit IT/digital rotations', rk='Secondary-source details; Kuwaitis only', rc='GOOD TARGET (Kuwaitis)', nt='', il='N', rl='Low'),

dict(c='Zain Group', ct='Telecom (regional)', ti='GROW Program - paid 3-month training+internship for graduates with disabilities', ot='Internship / Training-to-Employment', co='Kuwait (group-wide: Bahrain, Sudan, South Sudan too)', ci='Kuwait City + group markets', rm='On-site', pr=2,
 ta='Telecom/tech/business (AI + data analysis training included)', tech='AI, data analysis, technical skills + innovation camp', ex='Fresh graduates with disabilities', dg='Bachelor', du='3 months paid internship + 1 month intensive training',
 sc=(13,8,8,10,9,7,3,3,1), sa='Paid internship', vi='Per group market', re='No', po='2026 cohort graduated (Jul 2026 news); next cohort expected', dl='Watch Zain careers/announcements', st='Annual - next cohort Unverified',
 u='https://kuwaittimes.com/article/46067/kuwait/other-news/zain-grow-program-opens-meaningful-career-pathways-for-graduates-with-disabilities/amp/', so='Kuwait Times (Jul 2026)',
 di='Medium', bs='Designed for fresh grads with disabilities', ca='Mentor assigned to every trainee; inclusive pipeline into Zain', le='Medium-High', cl='Medium (620 applicants group-wide)',
 rq='Graduate with disability; English; group markets', sk='AI/data literacy, workplace skills',
 wy='Rare dedicated paid pathway with 1:1 mentorship for graduates with disabilities', rk='Niche eligibility; annual', rc='HIGH PRIORITY for eligible graduates', nt='2026 cohort: 20 participants across Zain markets.', il='U', rl='Low'),

dict(c='Zain Jordan', ct='Telecom', ti='Business Systems Intern - 1-year contract (Zain Youth Program)', ot='Internship (1 year)', co='Jordan', ci='Amman', rm='On-site', pr=2,
 ta='Technology & Digital Innovation', tech='Enterprise systems, databases, integrations', ex='Fresh graduate', dg='Bachelor CS/CE/related', du='1 year internship contract',
 sc=(12,10,6,10,9,7,3,2,1), sa='Internship salary (not published)', vi='No (Jordan-based)', re='No', po='Listing active ~Jul 2026 (29 days old)', dl='Check listing', st='OPEN (recent listing)',
 u='https://www.bayt.com/en/jordan/jobs/engineering-internships-jobs/', so='Bayt listing ZAIN2373 (Jul 2026) + careers.zain.com',
 di='Medium', bs='Yes - explicitly for fresh graduates', ca='A full YEAR inside a telecom technology department', le='High - sustained real-system exposure', cl='Medium-High',
 rq='CS/CE degree; SQL/ORACLE basics; English', sk='SQL/Oracle, scripting, systems thinking',
 wy='Rare 12-month paid internship contract for fresh grads in Amman', rk='Conversion to permanent not guaranteed', rc='APPLY NOW (Jordan-based fresh grads)', nt='Zain Jordan regularly posts 1-year intern roles (DevOps/Billing, Integration & Backend).', il='U', rl='Low'),

dict(c='Zain Jordan', ct='Telecom', ti='DevOps & Billing System Intern / Integration & Backend Developer Internship', ot='Internship (1 year)', co='Jordan', ci='Amman', rm='On-site', pr=2,
 ta='Backend / DevOps / Integrations', tech='Oracle PL/SQL, .NET/.NET Core, REST APIs, Unix/Linux, BSS/CRM/ERP', ex='Fresh graduate', dg='Bachelor CS/CE/related', du='1 year internship contract (Zain Youth Program)',
 sc=(12,12,6,10,8,7,4,2,1), sa='Internship salary (not published)', vi='No', re='No', po='Previous cycle closed 25 Sep 2025; new intern postings recur', dl='Watch careers.zain.com', st='Annual/recurring - Unverified',
 u='https://careers.zain.com/vacancy/169523', so='Zain careers official vacancy page + LinkedIn listing',
 di='Medium', bs='Yes - fresh grads', ca='Real BSS/OSS integration work: billing, provisioning, CRM', le='High - telecom backend engineering depth', cl='Medium-High',
 rq='Oracle/SQL, shell scripting, Linux basics', sk='Oracle PL/SQL, .NET, REST APIs, Linux',
 wy='Genuine backend/integration engineering internship (not shadowing) with 12-month runway', rk='Cycles intermittent; Jordan-based', rc='HIGH PRIORITY - set alert on Zain careers (Jordan)', nt='', il='U', rl='Low'),
]
