# -*- coding: utf-8 -*-
# Phase 7-10 data: Americas, AU/NZ, Remote Global, Open Source, Government/global
ROWS = [

# ==================== NORTH AMERICA (Priority 4) ====================
dict(c='Microsoft', ct='Big tech', ti='Explore Microsoft (software internship for first/second-year students)', ot='Internship', co='USA (Redmond/Atlanta) + Canada/Mexico/India campuses', ci='Redmond etc.', rm='On-site', pr=4,
 ta='Software engineering + PM exploration', tech='Real product team projects; Azure ecosystem', ex='First/second-year undergraduates (no experience expected)', dg='Enrolled bachelor (any major can apply)', du='12 weeks summer (US); 8 weeks India',
 sc=(14,12,8,11,10,10,4,5,1), sa='Microsoft intern pay (top-tier US intern scale)', vi='US/Canada/India work authorization rules; program is for students in those regions', re='Housing support typical', po='Annual (page live 2026)', dl='Typically fall for next summer', st='Annual - watch careers.microsoft.com',
 u='https://careers.microsoft.com/v2/global/en/exploremicrosoft', so='Microsoft official Explore program page (verified live)',
 di='Hard', bs='Perfectly - designed for early students, any major', ca='Official early-exploration pipeline into Microsoft SWE', le='Very high - pod projects in real teams', cl='Very high',
 rq='First/second-year status in US/CA/MX/IN; interest in tech', sk='One language + DSA basics',
 wy='The canonical beginner big-tech internship', rk='Regional student status required; closed until next cycle', rc='HIGH PRIORITY for early students in US/CA/IN - apply fall', nt='University Grad SWE roles are the post-graduation track.', il='N', rl='Low'),

dict(c='Google', ct='Big tech', ti='Software Engineer, University Graduate / STEP Intern', ot='Graduate Program / Internship', co='US + global offices (incl. Dublin, Munich)', ci='Multiple', rm='On-site/Hybrid', pr=4,
 ta='Product engineering at scale', tech='C++/Java/Python, distributed systems', ex='New grads (BS/MS/PhD); STEP for 1st/2nd-year students', dg='Degree in CS/related (in progress for STEP)', du='Permanent (new grad) / ~12 weeks (STEP)',
 sc=(13,14,8,12,7,10,5,5,2), sa='Top-of-market (US new grad ~USD 180k+ TC; regional scales elsewhere)', vi='Sponsorship widely available for full-time roles', re='Relocation packages standard', po='2026 university-grad requisition seen (specific posting since taken down - cycles continue)', dl='Rolling per office; Europe apps often Sep-Nov', st='Annual/rolling - Unverified current reqs',
 u='https://www.google.com/about/careers/applications/jobs/results/', so='Google careers jobs portal (2026 SWE University Graduate req seen; later removed = cycle continues)',
 di='Very hard', bs='Needs strong DSA; no work experience required', ca='Global gold-standard engineering entry', le='Very high', cl='Extreme',
 rq='DSA mastery; behavioral; degree timeline', sk='DSA (LeetCode), one OOP language, system basics',
 wy='Best-documented conversion pipeline: intern -> return offer -> SWE', rk='Extreme selectivity; STEP regional eligibility', rc='HIGH PRIORITY only if DSA-ready', nt='Watch google.com/careers -> Students -> STEP & University Graduate.', il='U', rl='Low'),

dict(c='Amazon', ct='Big tech', ti='SDE Internship & New-Grad SDE I (university talent)', ot='Internship / Entry-Level Job', co='US + global (EU, ME, AU offices incl. Brisbane 2026 grad req seen)', ci='Multiple', rm='On-site/Hybrid', pr=4,
 ta='Retail/AWS platform engineering', tech='Java/C++, AWS, distributed systems', ex='Students & grads within 12-24 months of graduation', dg='Enrolled/completed CS-related degree', du='Intern ~12-16 weeks; SDE I permanent',
 sc=(13,14,8,12,7,10,4,5,2), sa='High (US SDE intern ~USD 9k/mo; regional scales vary)', vi='Sponsorship common for full-time (region-dependent)', re='Standard packages', po='AU 2026-grad req closed 18 Feb 2026; cycles recur year-round globally', dl='Rolling/annual per region', st='Annual - regional windows vary',
 u='https://au.gradconnection.com/employers/amazon/jobs/amazon-software-development-engineer-2026-graduate-stores/', so='Amazon 2026 graduate SDE requisition (AU) + global university hiring',
 di='Hard', bs='No work experience required for internships/new-grad', ca='SDE I -> SDE II documented ladder; massive scale', le='Very high', cl='Very high',
 rq='DSA; Leadership Principles prep', sk='Java/C++/Python, DSA, SQL',
 wy='Largest volume of verified big-tech entry hiring globally', rk='High interview load; on-site (relocation) model', rc='HIGH PRIORITY if DSA-ready - watch amazon.jobs university section', nt='', il='U', rl='Low'),

dict(c='Salesforce (Futureforce)', ct='Big tech (SaaS)', ti='Futureforce University Recruiting - SWE internships & new grad', ot='Internship / Graduate Program', co='US (SF HQ) + global', ci='San Francisco + hubs', rm='Hybrid', pr=4,
 ta='CRM platform engineering', tech='Java, JavaScript, SQL, Agentforce/AI stack', ex='Students (BS CS/related) & new grads', dg='Enrolled or recent degree', du='Summer internship (~10-12 weeks); new-grad permanent',
 sc=(13,13,8,11,7,9,4,5,1), sa='USD 50-58/h intern rate seen for 2026 postings', vi='US work authorization needed for US program', re='Events supported (Tech Accelerator all-expenses trip pattern)', po='2026 summer intern cycle closed; Launchpad pre-internship waitlist live', dl='Annual - apps ~Aug-Apr cycle', st='Annual - 2026 closed; 2027 watch',
 u='https://info.codepath.org/futureforce-tech-launchpad', so='Salesforce Futureforce / CodePath Launchpad pages (2026)',
 di='Hard', bs='Students yes', ca='Return-offer culture; structured mentor program', le='Very high', cl='High',
 rq='OOP/algorithms; enrollment status', sk='Java, JS, SQL, DSA',
 wy='Structured SaaS giant early-career brand (Futureforce)', rk='US-centric; annual window', rc='GOOD TARGET for US students (2027 cycle)', nt='Futureforce Tech Launchpad = 10-week paid pre-internship for rising juniors (2026 cohort full/waitlist).', il='N', rl='Low'),

dict(c='Shopify', ct='Big tech (commerce)', ti='Engineering Internships (4-month paid) + Dev Degree', ot='Internship', co='Canada (remote-first company; Ottawa/Toronto hubs)', ci='Canada (remote-eligible)', rm='Remote/Hybrid', pr=4,
 ta='Commerce platform engineering', tech='Ruby on Rails, React, GraphQL', ex='Students, recent grads, early-career switchers', dg='Not strictly required (skills-first)', du='4-month paid internships (Jan & summer cohorts)',
 sc=(14,15,8,12,9,9,4,4,1), sa='Shopify intern pay (top Canadian scale, ~CAD 7-9k/mo typical)', vi='Canada work eligibility needed (interns)', re='No', po='Winter cohort apps ~Sep; summer ~Jan-Mar', dl='Per cohort (e.g., data winter cohort closed 15 Sep 2025 pattern)', st='Annual cohorts - watch shopify.com/careers',
 u='https://www.shopify.com/careers/extraordinary_0dac47b1-3275-48ce-aaca-10e1e18294e4', so='Shopify official early-career page (verified)',
 di='Hard', bs='Life Experience track welcomes non-traditional backgrounds', ca='Dev Degree = earn CS degree while working at Shopify', le='Very high - production Rails/React', cl='Very high',
 rq='Portfolio/projects; SQL/Rails basics help; Canada work rights (for internships)', sk='Ruby or JS, SQL, Git',
 wy='Remote-first engineering internships from a top global commerce platform', rk='Canada work eligibility; competitive', rc='HIGH PRIORITY (Canada-eligible) - next cohort apps fall/winter', nt='Dev Degree = 3-4 yr work+study program (Canada).', il='N', rl='Low'),

# ==================== AUSTRALIA / NZ (Priority 4) ====================
dict(c='Atlassian', ct='Big tech (AU)', ti='University Graduate - Software Engineer (Sydney, also remote zones)', tl='', ot='Graduate Program', co='Australia', ci='Sydney (+ remote zones)', rm='Hybrid/Remote zones', pr=4,
 ta='Collaboration software engineering', tech='Java/Kotlin, React, cloud (AWS)', ex='Final-year students & new grads', dg='Bachelor/Master CS-related', du='Permanent grad roles + internships',
 sc=(13,14,8,12,7,9,4,5,2), sa='Grad ~AUD 85-90k base + super (market data); TC high later', vi='485/482 visa paths; Atlassian sponsors skilled hires', re='Sydney relocation', po='Annual cycles (apps ~Feb-Apr for following year; intern apps earlier)', dl='Check atlassian.com/careers/university', st='Annual - Unverified current window',
 u='https://whatisthesalary.com/it-salaries/software-engineer-salary-in-australia/', so='AU 2026 salary report naming Atlassian/Canva grad bands; official atlassian.com careers',
 di='Hard', bs='For new grads with solid DSA', ca='Australia flagship tech employer; grad comp leader', le='Very high', cl='Very high',
 rq='DSA; behavioral (values fit)', sk='Java/Kotlin or Python, DSA, SQL',
 wy='Highest-profile AU engineering grad destination', rk='Australia relocation; annual timing', rc='HIGH PRIORITY (if AU-eligible) - apps open ~Feb 2027', nt='Atlassian also hires remotely across AU zones.', il='U', rl='Low'),

dict(c='Canva', ct='Big tech (AU)', ti='Graduate Software Engineer program (Sydney)', ot='Graduate Program', co='Australia', ci='Sydney', rm='Hybrid', pr=4,
 ta='Design platform engineering', tech='Java, React, Go, cloud', ex='New grads', dg='CS-related degree', du='Permanent grad track',
 sc=(13,14,8,12,7,9,4,5,2), sa='Grad >AUD 100k TC reported (market data)', vi='AU visa paths; Canva sponsors selectively', re='Sydney relocation', po='Annual cycles', dl='Check canva.com/careers', st='Annual - Unverified',
 u='https://whatisthesalary.com/it-salaries/software-engineer-salary-in-australia/', so='AU 2026 salary report + Canva careers reputation',
 di='Hard', bs='New grads', ca='Top AU culture + comp', le='Very high', cl='Very high',
 rq='DSA; product sense', sk='Java/Go, React, SQL',
 wy='Elite AU grad program with strong conversion culture', rk='Relocation; timing', rc='HIGH PRIORITY (AU-eligible) - watch Feb 2027 intake', nt='', il='U', rl='Low'),

dict(c='Xero', ct='Scaleup (accounting SaaS, NZ/AU)', ti='Graduate Software Engineer (NZ/AU)', ot='Graduate Program', co='New Zealand/Australia', ci='Wellington/Auckland/Melbourne', rm='Hybrid', pr=4,
 ta='SaaS platform engineering', tech='C#/.NET, React, AWS', ex='New grads', dg='CS-related', du='Permanent grad track',
 sc=(12,12,7,11,8,8,4,4,2), sa='Grad ~NZD/AUD 65-75k+ (market data)', vi='NZ Green List tech roles facilitate residence paths; Xero hires internationally', re='Possible', po='Annual cycles', dl='Check xero.com careers', st='Annual - Unverified',
 u='https://www.reddit.com/r/cscareerquestionsOCE/comments/tgsjqq/melbourne_grad_pay/', so='ANZ grad-pay discussions + Xero careers reputation',
 di='Medium-Hard', bs='New grads', ca='Stable SaaS scaleup; NZ immigration advantages for tech', le='High', cl='Medium-High',
 rq='CS degree; C#/.NET interest', sk='C#, SQL, Git, cloud basics',
 wy='NZ flagship SaaS with junior-friendly culture + immigration upside', rk='Lower pay than AU unicorns; annual', rc='GOOD TARGET (NZ/AU-eligible)', nt='', il='U', rl='Low'),

# ==================== REMOTE GLOBAL / OPEN SOURCE (Priority 5) ====================
dict(c='Canonical', ct='Open-source company (Ubuntu)', ti='Graduate Software Engineer - Open Source & Linux (fully remote worldwide)', ot='Graduate Program / Junior Job', co='Global (remote)', ci='Remote - worldwide', rm='Remote', pr=5,
 ta='Linux/OS, cloud, AI platform engineering', tech='Ubuntu, Linux, Python, Go, Rust, C/C++, Kubernetes', ex='Fresh graduates (batches 2024/2025/2026 eligible)', dg='STEM degree (strong academics)', du='Permanent, fully remote',
 sc=(13,15,8,12,9,8,4,4,5), sa='Location-indexed salary (competitive globally; ~USD 60-100k+ equivalents per region)', vi='No visa needed - hire locally in your country', re='N/A (remote) + international sprints', po='Active 2026 hiring (June 2026 postings seen)', dl='Rolling', st='OPEN (verified active 2026)',
 u='https://www.jobinsider.in/jobs/canonical-remote-software-engineer-job-26/', so='Canonical 2026 graduate SWE hiring coverage (multiple boards); official canonical.com/careers',
 di='Hard (academics + essays + interviews)', bs='Explicitly for 2025/2026 fresh grads', ca='Work with engineers from 75+ countries; USD 2,000 learning budget; real open-source product (Ubuntu)', le='Very high - low-level to cloud-native breadth', cl='High',
 rq='Excellent academics; Linux familiarity; strong written English; self-direction', sk='Python or Go/C++, Linux/Git, OSS contribution history',
 wy='The best fully-remote, globally-open graduate engineering job found in this research', rk='High written-communication bar; remote isolation; interview gauntlet', rc='APPLY NOW - TOP REMOTE TARGET', nt='Learning budget USD 2,000; travel to team sprints.', il='Y', rl='Low'),

dict(c='MLH Fellowship', ct='Open-source fellowship (Major League Hacking)', ti='12-week open-source software engineering fellowship (remote, year-round batches)', ot='Open Source Program', co='Global (remote)', ci='Remote', rm='Remote', pr=5,
 ta='Open source SWE / SRE / software engineering tracks', tech='Git/GitHub PRs, code review, CI, varied OSS stacks', ex='Beginners in OSS welcome (pods of 8-10, daily standups)', dg='No degree requirement', du='12 weeks (Spring/Summer/Fall batches)',
 sc=(13,14,8,7,9,7,5,4,5), sa='Up to USD 5,000 need-based stipend (optional application)', vi='Remote - no visa', re='N/A', po='Rolling batches; fall batch applications active 2026', dl='Per batch (rolling; seats fill)', st='OPEN (rolling batches)',
 u='https://fellowship.mlh.io/', so='MLH Fellowship official + 2026 program guides',
 di='Medium', bs='Yes - explicitly beginner-friendly in OSS', ca='Real contributions to OSS that companies depend on; interview-skip partnerships historically', le='Very high - Git/PR/code-review discipline in the open', cl='Medium-High',
 rq='Git basics; one language; time commitment', sk='Git/GitHub workflow, Python/JS, reading large codebases',
 wy='The fastest legitimate way for a beginner to gain production-like OSS experience from anywhere', rk='Stipend need-based (not guaranteed); not a job', rc='APPLY NOW - TOP PORTFOLIO BUILDER', nt='Tracks: Open Source, SRE, Software Engineering.', il='Y', rl='Low'),

dict(c='Google Summer of Code (GSoC)', ct='Google-run OSS program', ti='GSoC - paid open-source contributions with mentoring orgs', ot='Open Source Program', co='Global (remote)', ci='Remote', rm='Remote', pr=5,
 ta='Open source development (700+ orgs)', tech='Varies by org (Python/JS/C++/Go...), Git, code review', ex='Newcomers to OSS welcome (<2 yrs OSS experience target)', dg='None (open to beginners & students 18+)', du='10-22 weeks (flexible), May-Nov pattern',
 sc=(12,15,9,8,7,9,5,4,5), sa='USD 1,500-6,600 stipend (PPP-adjusted by country)', vi='Remote - no visa', re='N/A', po='2026 cycle ran; 2027 cycle: org list ~Feb-Mar, proposals ~Mar-Apr', dl='2027 proposals expected Mar-Apr 2027', st='Annual - 2026 cycle complete',
 u='https://summerofcode.withgoogle.com/', so='GSoC official program + 2026 program guides',
 di='Medium-Hard (proposal-driven)', bs='Designed for newcomers with <2 yrs OSS', ca='Gold-standard CV signal; many orgs hire past contributors', le='Very high - real OSS engineering with a named mentor', cl='High (proposal quality decides)',
 rq='Pick org early; contribute pre-application; strong proposal', sk='Git, one stack deeply, technical writing',
 wy='Best mentorship-per-dollar program in open source; global access', rk='Annual; unpaid prep period; competitive proposals', rc='HIGH PRIORITY - start contributing to a GSoC org NOW for 2027', nt='Stipend scaled by region.', il='Y', rl='Low'),

dict(c='Outreachy', ct='Non-profit OSS internship', ti='Paid remote OSS internships for underrepresented groups', ot='Open Source Program (paid internship)', co='Global (remote)', ci='Remote', rm='Remote', pr=5,
 ta='Open source software (and non-coding tracks)', tech='Git, OSS stacks; mentor-led projects', ex='Beginners welcome (underrepresentation criteria apply)', dg='No degree requirement', du='3 months full-time (Dec-Mar and May-Aug cohorts)',
 sc=(14,14,9,8,8,7,5,5,5), sa='USD 7,000 total stipend', vi='Remote - no visa', re='N/A + event travel funding', po='Winter cohort initial applications 24-31 Aug 2026 (just closed); next window ~Jan-Feb 2027 (May cohort)', dl='Next application window expected early 2027', st='Closed for winter 2026 - next cohort apps early 2027',
 u='https://www.outreachy.org/', so='Outreachy official + Aug 2026 application guides',
 di='Medium (essay + contribution tasks)', bs='Yes - diversity-focused beginner support', ca='Many interns hired afterward by sponsor organizations (documented)', le='Very high - 1:1 mentor on real OSS', cl='Medium-High',
 rq='Eligibility (underrepresented in tech where you live); essays; contribution period tasks', sk='Git, one language; essay preparation',
 wy='Highest-stipend remote OSS internship with deep mentorship', rk='Eligibility criteria; annual windows; just closed for winter', rc='HIGH PRIORITY (eligible applicants) - prep for early-2027 window', nt='Two cohorts per year; USD 7,000 stipend.', il='Y', rl='Low'),

dict(c='LFX Mentorship (Linux Foundation)', ct='Open-source foundation', ti='CNCF/LF mentorship terms (cloud-native OSS, paid)', ot='Open Source Program', co='Global (remote)', ci='Remote', rm='Remote', pr=5,
 ta='Cloud-native / Kubernetes / Linux / networking OSS', tech='Kubernetes ecosystem, Go, CI/CD, Linux', ex='Beginners-to-intermediate; per-project', dg='None strict', du='12 weeks full-time (or 24 part-time); 3 terms/year',
 sc=(13,14,8,9,7,8,5,4,5), sa='USD 3,000-6,600 per term (PPP-adjusted)', vi='Remote - no visa', re='N/A', po='Term 3 (Sep-Nov 2026) applications ran mid-2026; terms recur', dl='Rolling per term', st='OPEN/recurring (check current term)',
 u='https://dev.to/yakhilesh/20-open-source-internship-programs-updated-for-2026-5h32', so='2026 OSS programs guide (LFX terms & stipends); official lfx.linuxfoundation.org',
 di='Medium', bs='Per project', ca='Direct pipeline into cloud-native jobs (Kubernetes ecosystem hiring)', le='Very high - infrastructure engineering', cl='Medium',
 rq='Go/Linux basics for most projects', sk='Go, Docker/Kubernetes, Linux',
 wy='Paid remote OSS with the strongest industry hiring signal in cloud-native', rk='Per-project selectivity; technical bar', rc='HIGH PRIORITY - pick a Term-3/2027 project now', nt='Includes Linux Kernel Mentorship track.', il='Y', rl='Low'),

dict(c='Elwood Technologies', ct='Fintech (institutional crypto trading infra)', ti='Graduate/Junior Software Engineer - Backend', ot='Graduate Program / Junior Job', co='UK (remote-listed)', ci='London (remote available)', rm='Remote/Hybrid', pr=5,
 ta='Trading infrastructure backend', tech='Backend rotations (Backend + Market Connectivity teams)', ex='Graduate/Junior', dg='CS/related', du='Permanent with rotations',
 sc=(10,15,7,10,7,7,4,5,4), sa='GBP 50,000 starting', vi='UK visa per company policy (Unverified)', re='Unclear', po='Posted ~26 days before Sep 2026 check', dl='Check listing', st='OPEN (recent listing, Aug 2026) - Unverified',
 u='https://web3.career/dev+junior+remote-jobs', so='web3.career junior-remote board (Aug 2026) - Elwood graduate SWE listing',
 di='Medium-Hard', bs='Graduate-labeled', ca='FCA-regulated institutional platform; structured rotations', le='High - low-latency trading infrastructure', cl='Medium-High',
 rq='Backend fundamentals; rotations flexibility', sk='Java/Go or Python, SQL, networking basics',
 wy='Graduate backend seat at GBP 50k with remote listing', rk='Crypto-adjacent volatility; visa unclear', rc='APPLY NOW (UK-eligible or remote-permitted)', nt='FCA-regulated firm (not a shady crypto project).', il='U', rl='Low'),

dict(c='PULSE (MENA)', ct='MENA tech (remote-first)', ti='Junior Front-End Developer (Remote, USD 45-65k)', ot='Junior Job', co='MENA (remote)', ci='Remote - MENA team', rm='Remote', pr=5,
 ta='Web front-end engineering', tech='Modern web UI, responsive/accessible apps', ex='Junior', dg='Not stated', du='Permanent, remote-first',
 sc=(7,13,6,7,8,4,4,4,4), sa='USD 45,000-65,000/year', vi='Remote - contract/hire per company setup (verify)', re='N/A', po='Posted 18 Jul 2026', dl='Check listing', st='OPEN (recent listing, Jul 2026) - Unverified',
 u='https://skillora.ai/jobs/remote-junior-software-engineer-jobs', so='Skillora remote junior board (Jul 2026) - PULSE MENA listing',
 di='Medium', bs='Junior-open, MENA team', ca='Remote front-end at US-range salary from MENA', le='Medium-High - modern UI engineering', cl='Medium',
 rq='React/modern JS portfolio; English', sk='React/TypeScript, Git, REST, accessibility',
 wy='MENA remote junior seat at internationally competitive pay', rk='Aggregator listing - verify company before applying (ask for contract details)', rc='APPLY NOW (portfolio-ready juniors in MENA)', nt='Timezone-friendly for Qatar/GCC residents.', il='Y', rl='Medium (verify company)'),

dict(c='ListLab', ct='Small product company', ti='Junior Software Developer - Remote (contract)', ot='Junior Job', co='Remote', ci='Remote', rm='Remote', pr=5,
 ta='Consumer web application', tech='Web stack (flexible by skills)', ex='Junior', dg='Not stated', du='Contract (full/part-time flexible)',
 sc=(6,12,5,6,8,3,4,3,4), sa='Contract rates (not published)', vi='Remote contracting (no visa)', re='N/A', po='Posted 25 Jul 2026', dl='Check listing', st='OPEN (recent listing) - Unverified',
 u='https://skillora.ai/jobs/remote-junior-software-engineer-jobs', so='Skillora remote junior board (Jul 2026)',
 di='Easy-Medium', bs='Yes - flexible title/commitment', ca='Real consumer app experience, flexible hours', le='Medium', cl='Low-Medium',
 rq='Web dev portfolio', sk='JS, Git, basic SQL',
 wy='Low-barrier remote junior seat with flexible terms', rk='Contract (no benefits); small company', rc='APPLY IF REQUIREMENTS MET (portfolio needed)', nt='', il='Y', rl='Medium (verify company)'),

dict(c='Storyteller', ct='Product company (Turkey, remote)', ti='Junior Web Developer - Remote', ot='Junior Job', co='Turkey (remote)', ci='Remote', rm='Remote', pr=5,
 ta='Mobile/web apps', tech='React, TypeScript, React Native, SQL', ex='Junior; no degree required', dg='No degree required', du='Permanent remote',
 sc=(5,11,5,6,9,3,4,3,4), sa='~EUR 23,000/year', vi='Remote contracting from most countries (verify)', re='N/A', po='2025-2026 board listing', dl='Check listing', st='Unverified',
 u='https://www.remoterocketship.com/jobs/junior-developer/', so='Remote Rocketship junior-developer board - Storyteller listing',
 di='Easy-Medium', bs='Yes - explicitly no degree', ca='Skills-first remote junior role', le='Medium', cl='Low-Medium',
 rq='React/TS portfolio', sk='React, TypeScript, SQL',
 wy='No-degree remote junior seat with mobile exposure', rk='Modest pay; verify employer legitimacy', rc='APPLY IF REQUIREMENTS MET', nt='', il='Y', rl='Medium (verify company)'),

dict(c='AWS re/Start', ct='Corporate training program (Amazon)', ti='Free cloud re-skilling bootcamp with employer interviews', ot='Bootcamp-to-Employment', co='Global (multiple countries incl. Qatar/GCC cohorts reported)', ci='Various cities', rm='On-site/Hybrid per cohort', pr=5,
 ta='Cloud computing foundations', tech='AWS, Linux, Python basics, networking', ex='Unemployed/underemployed beginners welcome', dg='No degree requirement', du='~12 weeks full-time + employer interview day',
 sc=(13,8,6,9,10,8,4,3,3), sa='Free program (some cohorts offer stipends)', vi='Per cohort country', re='No', po='Cohorts run year-round by country', dl='Per cohort', st='Open (rolling cohorts) - check local cohort',
 u='https://www.nucamp.co/blog/coding-bootcamp-qatar-qat-top-10-tech-internships-offered-in-qatar', so='Nucamp Qatar tech guide (AWS re/Start as no-cost Qatar pathway) + official aws.amazon.com/training/restart',
 di='Easy-Medium', bs='Yes - designed for complete career changers', ca='Direct line to AWS-partner employer interviews', le='Medium-High - cloud foundations + labs', cl='Medium',
 rq='Commitment; English; local cohort availability', sk='Linux, Python basics, AWS core services',
 wy='Free Amazon-backed cloud bootcamp available in the Gulf', rk='Cloud-ops oriented (not pure SWE); cohort availability varies', rc='GOOD TARGET as cloud entry + complement to dev skills', nt='Pairs well with GitHub projects for junior cloud-adjacent dev roles.', il='U', rl='Low'),

dict(c='Mindrift (Toloka)', ct='AI gig platform', ti='Freelance Full-Stack Web App Developer (AI Pilot)', ot='Freelance/Gig (flagged)', co='Remote (incl. Qatar listings)', ci='Remote', rm='Remote', pr=5,
 ta='AI-assisted web app development tasks', tech='JS/TS, Python/Node', ex='Flexible', dg='Not stated', du='Gig-based',
 sc=(3,6,2,2,6,3,4,2,4), sa='Per-task gig rates (not published)', vi='Remote contracting', re='N/A', po='Live listings 2026', dl='N/A', st='Open (gig marketplace)',
 u='https://www.bayt.com/en/qatar/jobs/software-development-intern-jobs/', so='Bayt listing (Mindrift/Tendem project, 2026)',
 di='Easy', bs='Not a career track', ca='Minimal: gig work, no mentorship or employment path', le='Low-Medium', cl='N/A',
 rq='JS/TS + Python/Node', sk='Not applicable for career goals',
 wy='None significant for a career track - included only to flag the category', rk='Gig economy: no training, no employment, unclear terms; do NOT treat as employment experience', rc='NOT SUITABLE (as career move) - listed for transparency', nt='Example of AI-gig listings that can waste job-seeker time; verify any "AI pilot" offer carefully.', il='Y', rl='Medium'),
]
