# -*- coding: utf-8 -*-
# Phase 4-6 data: Egypt, Turkey, Europe
ROWS = [

# ==================== EGYPT (Priority 2) ====================
dict(c='ITI - Information Technology Institute (MCIT Egypt)', ct='Government institute', ti='9-Month Professional Training Program - Intake 47', ot='Bootcamp-to-Employment (government, free)', co='Egypt', ci='Cairo (Smart Village) + branches', rm='On-site', pr=2,
 ta='Software engineering, data, AI, UX, games (30+ tracks)', tech='Full software engineering curriculum + team capstone projects', ex='Graduates within past 5 years; grade Good+; military status resolved (males)', dg='Bachelor (any for some tracks; CS/Eng for hardcore tracks)', du='9 months full-time (Intake 47: Oct 2026 - Jun 2027)',
 sc=(18,12,8,14,9,8,4,3,2), sa='Free government scholarship (no salary; stipends vary by era)', vi='No (Egypt-based)', re='No', po='Applications 16-29 Jul 2026', dl='CLOSED 29 Jul 2026 - Intake 48 expected mid-2027', st='Closed (annual intake) - plan for 2027',
 u='https://egyincs.me/iti-professional-training-program-9-month/', so='ITI Intake-47 admission guide + ITI official (iti.gov.eg)',
 di='Medium-Hard (multi-stage exams)', bs='Yes - designed for fresh graduates incl. career shifters', ca='Legendary Egyptian pipeline into software jobs; strong alumni network in GCC/Europe; ~95% employment reported (secondary)', le='Very high - intensive full-time engineering training + real projects', cl='High',
 rq='IQ/English + track exams + technical interview; full-time commitment; own laptop', sk='Pick track (e.g., Java/Python web, data); algorithms basics before exams',
 wy='The single strongest training-to-employment institution for Egyptian graduates', rk='2026 window just closed; 9 months without salary; Egypt-based', rc='TOP TARGET FOR EGYPTIANS - prepare for Intake 48 (Jul 2027)', nt='Accredited toward Master-level study with partner universities.', il='U', rl='Low'),

dict(c='DEPI - Digital Egypt Pioneers Initiative (MCIT)', ct='Government initiative', ti='DEPI rounds - Software Development / AI / Data tracks', ot='Government Program (free training + freelance coaching)', co='Egypt', ci='Online + hubs', rm='Remote/Online', pr=2,
 ta='AI & Data Science, Software Development, DevOps, Data Analytics', tech='Track-based (DevOps, AI System Developer, etc.)', ex='Graduates/students; track access depends on faculty background', dg='Bachelor students/graduates (all faculties; tracks mapped to background)', du='Foundation 6 months (4 learning + 2 freelance coaching) / Industry track 4 months',
 sc=(14,8,6,8,10,7,4,3,2), sa='Fully funded (free)', vi='No', re='No', po='Rounds open periodically; latest round closed - new phase announced soon', dl='Watch depi.gov.eg for next registration', st='Rolling rounds - current round closed',
 u='https://depi.gov.eg/', so='DEPI official site + university announcements',
 di='Easy-Medium (monitored 45-min English/technical exam)', bs='Very - built for youth across faculties', ca='Free national upskilling with freelance/employment orientation', le='Medium-High - structured tracks + assessments', cl='Medium',
 rq='National ID; one track choice; non-retakable exam', sk='English + track fundamentals before assessment',
 wy='Zero-cost government pathway into software/AI skills with freelance income coaching', rk='Training-heavy, employment not guaranteed; rounds fill fast', rc='HIGH PRIORITY (Egyptians) - register the day next round opens', nt='LinkedIn page confirms rounds open/close sequentially.', il='U', rl='Low'),

dict(c='talabat (Delivery Hero)', ct='Scaleup (regional delivery leader)', ti='talabatYouth - Engineering Graduate Program (Internship, Cairo)', ot='Graduate Program / Internship', co='Egypt', ci='Cairo', rm='On-site/Hybrid', pr=2,
 ta='Backend engineering (distributed systems)', tech='.NET, Golang, C#, cloud, distributed systems, XP practices', ex='Graduates 2024-2026 (students eligible); GPA >= 3.5', dg='Bachelor CS/related', du='6 months',
 sc=(14,14,7,14,8,7,4,3,2), sa='Paid internship (figure not published)', vi='No', re='No', po='Cycles recur; latest Cairo posting expired after 2026 transition plan', dl='Watch careers.deliveryhero.com', st='Annual - last posting expired; program confirmed to convert interns to permanent roles',
 u='https://careers.deliveryhero.com/job/talabatyouth-engineering-graduate-program-internship-cairo-in-cairo-egypt-jid-9668', so='Delivery Hero official careers (talabatYouth)',
 di='Medium-Hard (GPA 3.5)', bs='Yes - built for graduates', ca='Official wording: successful interns transition into a permanent role', le='High - pairing with engineers, XP, real backend systems', cl='High',
 rq='GPA 3.5; fluent English; extracurriculars; backend + cloud basics', sk='C# or Go, REST, SQL, testing basics',
 wy='Explicit internship-to-permanent engineering pathway at a regional tech leader', rk='GPA bar; cycles intermittent; expired now - set job alert', rc='HIGH PRIORITY - set alert for next talabatYouth cycle', nt='Data Graduate Internship variant also exists.', il='U', rl='Low'),

dict(c='Paymob', ct='Scaleup (MENA payments)', ti='Tech Internship 2026 (Backend Python / Frontend / iOS & Android / Pentesting)', ot='Internship', co='Egypt', ci='Cairo', rm='Hybrid', pr=2,
 ta='Payments platform engineering', tech='Python backend, frontend, mobile, security', ex='Students/recent grads', dg='CS/related (in progress OK)', du='Summer internship cycle',
 sc=(12,12,7,10,8,6,4,2,2), sa='Paid (not published)', vi='No', re='No', po='2026 cycle listed in Egyptian internships guide (deadline was ~15 Jul 2026)', dl='Closed for 2026 - watch 2027', st='Closed (annual) - Unverified next date',
 u='https://github.com/dinaashraf20003/Software-Internship-Guide', so='Community-maintained 2026 Egyptian internships guide (GitHub)',
 di='Medium', bs='Yes - internships by design', ca='Leading fintech scaleup; strong Egypt alumni pipeline', le='High - real product teams', cl='High',
 rq='Coding assessments; fundamentals', sk='Python/Django or mobile stack, Git, SQL',
 wy="Egypt's flagship fintech with a real multi-track tech internship", rk='Annual window missed for 2026; competitive', rc='GOOD TARGET for Summer 2027', nt='Confirm via paymob.com careers.', il='U', rl='Low'),

dict(c='Nawy', ct='Scaleup (proptech)', ti='Summer 2026 Internship (engineering & others)', ot='Internship', co='Egypt', ci='Cairo', rm='Hybrid', pr=2,
 ta='Prop-tech platform', tech='Web stack (Node/React family)', ex='Students/fresh grads', dg='CS/related', du='Summer cycle',
 sc=(11,11,6,9,8,6,4,2,2), sa='Not published', vi='No', re='No', po='2026 cycle listed in guide', dl='Check listing (2026 cycle likely closed)', st='Closed/Unverified for 2026',
 u='https://github.com/dinaashraf20003/Software-Internship-Guide', so='Egyptian internships guide (GitHub) - Nawy listing',
 di='Medium', bs='Yes', ca='Well-funded product company; strong engineering culture reputation', le='Medium-High', cl='Medium-High',
 rq='Assessments; portfolio', sk='JS/TS, React, Node, SQL',
 wy='Top Egyptian product scaleup opening annual internships', rk='Cycle timing; competitive', rc='GOOD TARGET for Summer 2027', nt='', il='U', rl='Low'),

dict(c='Thndr', ct='Startup (fintech broker)', ti='Data Engineering Intern - Graduate Program', ot='Internship / Graduate Program', co='Egypt', ci='Cairo', rm='Hybrid', pr=2,
 ta='Data engineering', tech='Python, SQL, pipelines, warehouse', ex='Fresh grads/students', dg='CS/related', du='Internship term',
 sc=(12,12,7,11,8,6,4,2,2), sa='Not published', vi='No', re='No', po='2026 cycle listed in guide', dl='Check listing', st='Unverified for current cycle',
 u='https://github.com/dinaashraf20003/Software-Internship-Guide', so='Egyptian internships guide (GitHub) - Thndr listing',
 di='Medium', bs='Yes', ca='Fast-growing fintech; data-heavy product', le='High - modern data stack', cl='Medium-High',
 rq='Python + SQL; assessments', sk='Python, SQL, dbt/airflow concepts',
 wy='Graduate-labeled data engineering seat at a leading Egyptian startup', rk='Small company; niche data focus', rc='GOOD TARGET', nt='', il='U', rl='Low'),

dict(c='Siemens EDA (DISW) Egypt', ct='Global tech (Siemens digital industries)', ti='SSP - R&D Software Development Intern / AI-ML Development Intern', ot='Internship', co='Egypt', ci='Cairo (El-Obour)', rm='On-site/Hybrid', pr=2,
 ta='R&D software + AI/ML', tech='C++/Python, AI/ML tooling, enterprise R&D practices', ex='Students (long-term internship)', dg='Enrolled CS/Engineering', du='Long-term internship (~6 months pattern)',
 sc=(13,12,8,10,8,9,4,2,2), sa='Paid (not published)', vi='No', re='No', po='2026 cycle listed in guide', dl='Check listings', st='Unverified for current cycle',
 u='https://github.com/dinaashraf20003/Software-Internship-Guide', so='Egyptian internships guide (GitHub) - Siemens SSP listings',
 di='Medium-Hard', bs='For strong students', ca='Global R&D exposure inside Egypt; strong brand', le='Very high - R&D engineering discipline', cl='High',
 rq='C++/Python strength; academic record', sk='C++, Python, algorithms, Git',
 wy='Multinational R&D internship from Egypt - rare quality', rk='Student-status requirement; long-term commitment', rc='GOOD TARGET (students)', nt='', il='U', rl='Low'),

dict(c='Amazon (Cairo)', ct='Big tech', ti='Applied Scientist Intern 2026 / SDE internships (Egypt)', ot='Internship', co='Egypt', ci='Cairo', rm='On-site', pr=2,
 ta='Applied AI / SDE', tech='Python/Java, ML, AWS scale systems', ex='Students (PhD/MSc for scientist; BSc for SDE paths)', dg='Enrolled degree', du='3-6 months',
 sc=(12,14,8,10,5,10,5,3,2), sa='Amazon intern pay scale (local)', vi='No', re='No', po='2026 cycle listed in guide', dl='Amazon internships run on annual cycles', st='Unverified for current cycle',
 u='https://github.com/dinaashraf20003/Software-Internship-Guide', so='Egyptian internships guide (GitHub) - Amazon Cairo listing',
 di='Hard (Amazon bar-raiser interviews)', bs='Needs strong DS/algorithms - open to students', ca='Global brand; converts well to full-time SDE offers', le='Very high', cl='Very high',
 rq='DSA mastery; English; enrolled student', sk='DSA (LeetCode), one OOP language, ML basics (scientist track)',
 wy='Amazon engineering internships based in Cairo', rk='Very competitive; interview-heavy', rc='HIGH PRIORITY if DSA-ready', nt='', il='U', rl='Low'),

dict(c='Ericsson (Egypt)', ct='Global telecom vendor', ti='AI Engineering Intern', ot='Internship', co='Egypt', ci='Cairo', rm='On-site', pr=2,
 ta='AI engineering (telecom)', tech='Python, ML, telecom data', ex='Students', dg='Enrolled CS/Engineering', du='Summer cycle',
 sc=(11,10,7,8,7,8,4,2,2), sa='Paid (not published)', vi='No', re='No', po='2026 cycle listed in guide', dl='Check listings', st='Unverified',
 u='https://github.com/dinaashraf20003/Software-Internship-Guide', so='Egyptian internships guide (GitHub)',
 di='Medium', bs='Yes for students', ca='Global vendor brand; AI + telecom', le='Medium-High', cl='Medium',
 rq='Enrolled student; Python', sk='Python, ML basics',
 wy='Global telecom vendor AI internship in Egypt', rk='Cycle timing', rc='GOOD TARGET', nt='', il='U', rl='Low'),

dict(c='Instabug', ct='Scaleup (mobile SDKs)', ti='Summer Internship Program (Egypt-based)', ot='Internship', co='Egypt', ci='Cairo', rm='Hybrid', pr=2,
 ta='Mobile tooling product engineering', tech='iOS/Android/backend, product teams', ex='Students/recent grads (Egypt-based)', dg='CS/related', du='Summer (~6-8 weeks)',
 sc=(12,12,7,9,8,6,4,2,2), sa='Paid (not published)', vi='No', re='No', po='2025 cycle opened Apr 2025; 2026 assumed similar - Unverified', dl='Watch instabug.com + social (opens ~Apr)', st='Annual - Unverified for 2026/27',
 u='https://x.com/HeshamMegid/status/1911711729647562993', so='Instabug official announcement (2025 cycle)',
 di='Medium', bs='Yes', ca='Beloved Egyptian product company; mentors across the product', le='High - product engineering with strong mentors', cl='High',
 rq='Egypt-based; coding assessments', sk='One mobile or backend stack, Git',
 wy='Top-tier Egyptian engineering culture internship ("learning from exceptional mentors")', rk='Annual; Egypt-only; competitive', rc='HIGH PRIORITY - watch for next cycle (April pattern)', nt='', il='U', rl='Low'),

dict(c='Nokia (Egypt)', ct='Global telecom vendor', ti='NI DS AI Summer Trainee', ot='Internship', co='Egypt', ci='Cairo', rm='On-site', pr=2,
 ta='AI / Data science (networks)', tech='Python, ML, network data', ex='Students', dg='Enrolled degree', du='Summer cycle',
 sc=(10,10,6,8,7,8,4,2,2), sa='Paid (not published)', vi='No', re='No', po='2026 cycle listed in guide', dl='Check listings', st='Unverified',
 u='https://github.com/dinaashraf20003/Software-Internship-Guide', so='Egyptian internships guide (GitHub)',
 di='Medium', bs='Yes', ca='Global vendor; AI + networking data', le='Medium-High', cl='Medium',
 rq='Enrolled student; Python', sk='Python, ML basics, SQL',
 wy='Global vendor AI trainee seat in Egypt', rk='Cycle timing', rc='GOOD TARGET', nt='', il='U', rl='Low'),

dict(c='e-finance', ct='State fintech group', ti='Summer Internship Program 2026', ot='Internship', co='Egypt', ci='Cairo', rm='On-site', pr=2,
 ta='Payments / gov-tech engineering', tech='Payment platforms, enterprise Java/.NET stacks', ex='Students', dg='Enrolled CS', du='Summer cycle',
 sc=(10,8,5,8,8,6,3,2,2), sa='Allowance (not published)', vi='No', re='No', po='2026 cycle in guide', dl='Check listings', st='Unverified',
 u='https://github.com/dinaashraf20003/Software-Internship-Guide', so='Egyptian internships guide (GitHub)',
 di='Medium', bs='Yes', ca='State-backed fintech scale; stable employer', le='Medium', cl='Medium',
 rq='Enrolled student', sk='Java/C#, SQL basics',
 wy='Large state fintech group with structured summer intake', rk='Less startup-modern stack', rc='GOOD TARGET', nt='', il='U', rl='Low'),

dict(c='Flash (Egypt)', ct='Startup (payments)', ti='Software Engineer Intern', ot='Internship', co='Egypt', ci='Cairo', rm='Hybrid', pr=2,
 ta='Payments engineering', tech='Web/backend stack', ex='Students/grads', dg='CS/related', du='Internship term',
 sc=(9,10,5,7,8,4,4,2,2), sa='Not published', vi='No', re='No', po='2026 cycle in guide', dl='Check listing', st='Unverified',
 u='https://github.com/dinaashraf20003/Software-Internship-Guide', so='Egyptian internships guide (GitHub)',
 di='Medium', bs='Yes', ca='Fintech startup engineering seat', le='Medium-High', cl='Medium',
 rq='Fundamentals; assessments', sk='JS/Node or Python, SQL',
 wy='Open SWE internship at Egyptian fintech', rk='Small company risk', rc='GOOD TARGET', nt='', il='U', rl='Low'),

dict(c='Misr Technology Services', ct='State-linked IT services', ti='2026 Summer Internship', ot='Internship', co='Egypt', ci='Cairo', rm='On-site', pr=2,
 ta='IT services / software', tech='Enterprise stacks', ex='Students', dg='Enrolled CS', du='Summer cycle',
 sc=(9,8,5,7,8,5,3,2,2), sa='Allowance (not published)', vi='No', re='No', po='2026 cycle in guide', dl='Check listing', st='Unverified',
 u='https://github.com/dinaashraf20003/Software-Internship-Guide', so='Egyptian internships guide (GitHub)',
 di='Easy-Medium', bs='Yes', ca='Stable state-linked IT employer', le='Medium', cl='Low-Medium',
 rq='Enrolled student', sk='Basic programming + SQL',
 wy='Accessible state-sector summer internship', rk='Limited modern-stack depth', rc='LOW PRIORITY - acceptable fallback', nt='', il='U', rl='Low'),

# ==================== TURKEY (Priority 2) ====================
dict(c='Patika.dev (with Trendyol / Hepsiburada / NewMind)', ct='Training-to-employment platform', ti='Free Skillcamp Bootcamps (Frontend/Fullstack/AI) + hiring pipelines', ot='Bootcamp-to-Employment', co='Turkey', ci='Online (Turkey-focused)', rm='Remote/Online', pr=2,
 ta='Frontend, fullstack, AI', tech='JavaScript, React, Node.js, MySQL/PostgreSQL, MongoDB, Docker', ex='Beginners accepted (selection per bootcamp)', dg='No strict degree bar', du='Weeks-long intensive bootcamps, rolling programs',
 sc=(13,9,6,10,9,6,4,3,2), sa='Free bootcamps (some sponsored by employers)', vi='Turkey-based hiring for pipelines', re='No', po='Rolling (2026 programs; some deadlines just passed, new ones open)', dl='Per-program (check bootcamp page)', st='Open (rolling programs) - per-cohort deadlines',
 u='https://www.patika.dev/bootcamp', so='Patika.dev official bootcamps page (verified live, 2026)',
 di='Medium', bs='Yes - beginner tracks available', ca='Employer-sponsored bootcamps historically feed Trendyol/Hepsiburada hiring', le='Medium-High - project-based with employer context', cl='Medium-High',
 rq='Turkish/English per program; assessments', sk='JS fundamentals before Frontend bootcamps',
 wy='Free employer-linked bootcamp ecosystem with real hiring stories', rk='Employment not guaranteed; Turkish-language content dominant', rc='GOOD TARGET (Turkey-based) - apply to open 2026 programs', nt='NewMind AI Fullstack Bootcamp covers JS/React/Node/SQL/Docker.', il='U', rl='Low'),

dict(c='Dream Games', ct='Startup (gaming unicorn, Istanbul)', ti='Junior developer pipeline (with Patika bootcamps)', ot='Junior Job / Bootcamp pipeline', co='Turkey', ci='Istanbul', rm='On-site', pr=2,
 ta='Game development', tech='C#, Unity, Java, Golang', ex='Junior (bootcamp-to-hire pipeline)', dg='Not strict (portfolio)', du='Permanent',
 sc=(10,13,7,10,8,6,3,3,2), sa='Reported TRY 40k-50k/month junior range (secondary)', vi='Turkey hiring', re='No', po='Rolling per market report (2026)', dl='Check careers', st='Unverified',
 u='https://www.nucamp.co/blog/top-10-tech-startups-hiring-junior-developers-in-turkey-in-2026', so='Nucamp Top-10 Turkey startups hiring juniors 2026',
 di='Medium-Hard', bs='Yes via bootcamp cohorts', ca='Structured junior onboarding called gold standard in Turkish gaming', le='High - production game engineering', cl='High',
 rq='C#/Unity portfolio; bootcamp completion helps', sk='C#, Unity, algorithms',
 wy='Unicorn that hires juniors through structured bootcamp cohorts', rk='Secondary source; gaming specialization', rc='GOOD TARGET (Turkey-based, game-inclined)', nt='', il='U', rl='Low'),

dict(c='Trendyol', ct='Scaleup (e-commerce, Turkey)', ti='Junior engineer rotations / bootcamp-linked hiring', ot='Junior Job', co='Turkey', ci='Istanbul (incl. Berlin/Ankara)', rm='Hybrid', pr=2,
 ta='E-commerce platform engineering', tech='Java, microservices, distributed systems', ex='Junior/bootcamp grads', dg='CS/related preferred', du='Permanent with rotations',
 sc=(10,12,6,9,7,7,4,3,2), sa='Reported TRY 42k-55k/month junior (secondary)', vi='Turkey hiring (Berlin office for seniors mostly)', re='Possible within group', po='Rolling', dl='Check careers', st='Unverified',
 u='https://www.nucamp.co/blog/top-10-tech-startups-hiring-junior-developers-in-turkey-in-2026', so='Nucamp Turkey guide 2026 + Trendyol-Patika bootcamp history',
 di='Medium-Hard', bs='Juniors hired via bootcamps/rotations', ca="Turkey's largest e-commerce tech org; internal rotations", le='High - large-scale systems', cl='High',
 rq='Java/CS fundamentals', sk='Java, Spring Boot, SQL, Docker',
 wy='Major regional tech employer with documented junior/bootcamp hiring history', rk='Competitive; secondary-source salary', rc='GOOD TARGET (Turkey-based)', nt='', il='U', rl='Low'),

# ==================== EUROPE (Priority 3) ====================
dict(c='Blip (Flutter Entertainment)', ct='Tech company (betting/gaming, Porto hub)', ti='BETa Program 2026 - 9-month paid junior program', ot='Graduate Program / Trainee (paid)', co='Portugal', ci='Porto', rm='On-site/Hybrid', pr=3,
 ta='Software engineering for global gaming platforms', tech='Java 21, Spring Boot, Kafka, Apache Flink (per employee reviews), modern automated tooling + AI-assisted workflows', ex='< 1 year professional tech experience (career starters)', dg='Engineering/STEM degree OR intensive tech reskilling program', du='9 months, paid, fixed-term',
 sc=(16,15,8,13,10,7,4,4,2), sa='Paid 9-month program (salary not published; Blip pay reported competitive)', vi='Portugal hiring; EU/visa rules apply (EU Blue Card not needed for EU; check PT visa)', re='Not advertised', po='Applications opened Jun 2026', dl='Recruitment runs Jun-Oct 2026 - OPEN NOW (program starts fall 2026)', st='OPEN (verified official page, Sep 2026)',
 u='https://www.blip.pt/jobs/jr137836/beta-program-2026/', so='Blip official careers page + devs.com.pt coverage (Jun 2026)',
 di='Medium', bs='Perfectly - built for career starters with <1 yr experience', ca='Real complex software engineering work for global platforms + structured growth track', le='Very high - real codebases + training paths + modern stack', cl='Medium (Porto-located)',
 rq='<1 yr tech experience; curiosity about AI-assisted development; critical thinking; English', sk='Java basics, Git, SQL, DSA fundamentals',
 wy='A rare 9-month PAID junior program explicitly designed for beginners - currently open', rk='Gaming/betting domain; fixed-term with conversion "possible" not guaranteed; relocation to Porto needed', rc='APPLY NOW - TOP GLOBAL TARGET FOR BEGINNERS', nt='Part of Flutter Entertainment Group; employees report strong technical growth.', il='U', rl='Low'),

dict(c='N26', ct='Scaleup (digital bank, Berlin)', ti='Junior Backend Engineer - Data Ingestion (visa sponsorship listed)', ot='Junior Job', co='Germany', ci='Berlin', rm='On-site/Hybrid', pr=3,
 ta='Backend engineering (data platform)', tech='Kotlin/Java, data pipelines, cloud', ex='Junior', dg='CS/related', du='Permanent',
 sc=(8,15,7,7,7,7,5,5,4), sa='Fintech junior scale (Berlin; not published per listing)', vi='Sponsorship signal listed on aggregator', re='Possible (Berlin relocation common)', po='Listed "Recently" as of Jul 2026', dl='Check listing', st='Open (recent listing) - Unverified',
 u='https://www.softwarecareers.co.in/jobs/germany', so='SoftwareCareers Germany board (Jul 2026) - N26 junior backend with sponsorship signal',
 di='Medium-Hard', bs='Junior-open', ca='English-first fintech in Berlin; sponsorship explicitly surfaced', le='High - modern data engineering', cl='Medium-High',
 rq='Strong OOP; data structures; English', sk='JVM language, SQL, Kafka/streaming basics, Docker',
 wy='One of the few verified junior + visa-sponsorship backend seats in EU tech', rk='Junior seats at N26 are rare and competitive', rc='HIGH PRIORITY (if EU-visa eligible path exists) - apply fast', nt='EU Blue Card IT threshold 2026: ~EUR 45,934/yr salary.', il='U', rl='Low'),

dict(c='SAP', ct='Enterprise software giant', ti='SAP Internship Experience Program (iXp) - global paid internships', ot='Internship', co='Germany (Walldorf) + global (US etc.)', ci='Walldorf + global offices', rm='Hybrid', pr=3,
 ta='Enterprise software engineering + business tracks', tech='Cloud, AI, Big Data, IoT, SAP stack', ex='Students & recent graduates (up to ~1 yr)', dg='Enrolled student or recent graduate', du='3-6 months (some 6-12), 20-40 h/week',
 sc=(13,12,8,9,8,9,4,4,3), sa='Paid; US rates $15-62/h posted; DE rates per IG Metall-typical', vi='Possible at some locations (Germany internship visa/Blue-Card-track after)', re='Not standard', po='Active recruiting (US posting began 8 Aug 2026)', dl='Rolling - multiple postings', st='OPEN (active postings, Aug-Sep 2026)',
 u='https://www.ziprecruiter.com/Jobs/Sap-Ixp-Intern', so='SAP iXp postings (US campuses) via university boards; official: jobs.sap.com search iXp',
 di='Medium', bs='Yes - built for students/recent grads', ca='Europe-leading software company; mentoring emphasized ("expert mentors")', le='High - enterprise product engineering', cl='High',
 rq='Enrollment/recent-grad status; English (German helps in Walldorf)', sk='Java/Python/JS, SQL, cloud basics',
 wy='Structured global paid internship at a European software giant, currently hiring', rk='Non-engineering tracks mixed in - pick SDE postings; conversion to full-time not guaranteed', rc='HIGH PRIORITY - apply on jobs.sap.com (iXp)', nt='SAP is among the most active German visa sponsors per 2026 reports.', il='U', rl='Low'),

dict(c='Adyen', ct='Enterprise fintech platform', ti='Graduate program (Software Engineering) - Amsterdam/Paris/B/etc.', ot='Graduate Program', co='Netherlands (Amsterdam HQ) + EU offices', ci='Amsterdam', rm='On-site', pr=3,
 ta='Payments platform engineering', tech='Java, PostgreSQL, in-house payments stack', ex='Final-year students & fresh graduates', dg='Bachelor/Master CS/Engineering', du='Permanent from day one with global onboarding cohort',
 sc=(15,15,8,12,7,9,5,5,3), sa='Top fintech grad comp (Amsterdam; ~EUR 50k+ typical per market data)', vi='Sponsorship common for EU hires (confirm per role)', re='Relocation to Amsterdam required if abroad', po='EU applications typically open Sep-Oct 2026 for 2027 start', dl='Opens ~Sep-Oct 2026', st='Annual - opens soon (2027 intake)',
 u='https://startup.jobs/graduate-java-software-engineer-adyen-681583', so='Adyen graduate listings + 2027 application-timeline guide',
 di='Hard (technical test in Java)', bs='Yes for graduates; expect rigorous process', ca='Work as full team member on one of the most respected in-house payment platforms', le='Very high - deep systems engineering culture', cl='Very high',
 rq='CS degree (about to obtain); Java technical test; relocation', sk='Java depth, algorithms, SQL, networking basics',
 wy='Elite EU engineering graduate route with full-time status from day one', rk='Applications open soon (timing); very selective; Java-centric', rc='HIGH PRIORITY - prepare Java + apply when 2027 intake opens (Sep-Oct 2026)', nt='', il='U', rl='Low'),

dict(c='Booking.com', ct='Big tech (travel)', ti='Software Engineer I - AI Application Platform', ot='Junior Job (SWE I)', co='Netherlands', ci='Amsterdam', rm='On-site/Hybrid', pr=3,
 ta='AI application platform engineering', tech='Python/Java, AI platform services, cloud at scale', ex='Early-career (SWE I level)', dg='CS/related', du='Permanent',
 sc=(9,15,7,8,5,9,4,5,3), sa='Booking scale (not published per listing)', vi='Sponsorship historically available at Booking Amsterdam', re='Amsterdam relocation typical', po='Seen live on eFinancialCareers (1 day old at check)', dl='Check listing', st='OPEN (recent listing, Sep 2026) - Unverified',
 u='https://www.efinancialcareers.it/jobs/graduate-software-engineer/in-netherlands', so='eFinancialCareers NL graduate-SWE board (Sep 2026)',
 di='Medium-Hard', bs='SWE I = early-career but not zero-experience', ca='One of the largest EU tech employers; AI platform work', le='High - large-scale production systems', cl='High',
 rq='1-2 yrs equivalent (internships/projects); strong coding', sk='Python or Java, SQL, cloud, testing',
 wy='Live early-career listing at an EU tech giant in AI domain', rk='SWE I bar is above pure beginner; visa per role', rc='APPLY NOW if you can pass mid-junior bar', nt='', il='U', rl='Low'),

dict(c='Accenture Ireland', ct='Global consultancy', ti='Software Engineering Graduate Programme (Dublin)', ot='Graduate Program', co='Ireland', ci='Dublin', rm='Hybrid', pr=3,
 ta='Client software engineering (multi-industry)', tech='Google/AWS/SAP/Microsoft/Oracle/Salesforce ecosystems', ex='Fresh graduates (min 2.2 degree)', dg='Bachelor (any technical-leaning)', du='Permanent contract; 2-3 year grad program; 3-4 weeks initial training',
 sc=(13,8,7,11,8,8,3,4,3), sa='EUR 32,000-35,000 start (Dublin, per Glassdoor)', vi='Ireland Critical Skills possible for non-EU (check per offer)', re='Not standard', po='Graduate applications closed (as of Aug 2026 page) - reopen ~Sep-Oct', dl='Applications close early-mid October (annual pattern)', st='Annual - 2026 closed; watch Sep/Oct 2026 for next',
 u='https://www.accenture.com/ie-en/careers/life-at-accenture/entry-level', so='Accenture Ireland official entry-level page + gradireland profile',
 di='Medium', bs='Yes - designed for grads, any tech background', ca='Big consultancy brand; client projects across industries', le='Medium-High - but real dev share varies by client', cl='High',
 rq='2.2 degree min; strengths-based + technical interview', sk='One language well + SQL; consulting communication',
 wy='Large annual graduate intake in EU tech-consulting hub with visa options', rk='Reddit alumni: many "SWE" grads land support/testing/ops work instead of dev; client assignment luck', rc='GOOD TARGET - apply when it reopens (Oct 2026), but prefer product companies if possible', nt='Streams: Software Engineering, Data & AI, Cyber, Consulting. Summer internship feeds final interviews.', il='U', rl='Low'),

dict(c='Sky UK', ct='Media/tech giant', ti='Software Engineering Graduate Programme', ot='Graduate Program', co='UK', ci='London (Osterley), Leeds, Livingston', rm='On-site/Hybrid', pr=3,
 ta='Media platform engineering', tech='Clean code, CI/CD, TDD, agile, security principles', ex='No experience required (any degree)', dg='Bachelor (any discipline - graduating soon)', du='7-month accelerated program with 5-week bootcamp, then permanent team placement',
 sc=(15,12,7,11,9,8,3,4,2), sa='GBP 32,000-38,000', vi='UK right to work needed (historically no sponsorship for this program)', re='No', po='Annual; last cycle closed (pre-register available)', dl='Typically opens autumn, closes ~Aug of following year', st='Annual - closed; pre-register',
 u='https://uk.prosple.com/graduate-employers/sky-uk/jobs-internships/software-engineering-graduate-programme-0', so='Sky UK official grad programme (via Prosple listing with full curriculum)',
 di='Medium', bs='Excellent - any degree, no experience required', ca='5-week bootcamp then real product delivery with experts', le='High - TDD/CI/CD/agile taught then applied', cl='High',
 rq='Graduating soon; coding aptitude; right to work in UK', sk='One modern language; agile basics',
 wy='Structured engineering bootcamp-to-team pathway at a major UK tech-media employer', rk='UK work rights required (no sponsorship advertised); annual window', rc='HIGH PRIORITY (UK work-rights holders) - pre-register now', nt='Digital Grad Programme (non-coding) also exists - avoid confusion.', il='N', rl='Low'),

dict(c='J.P. Morgan (SEP)', ct='Global bank', ti='Software Engineer Program (global graduate, 2-year)', ot='Graduate Program', co='UK (London/Glasgow/Bournemouth) + global incl. US, ME offices', ci='Multiple', rm='On-site/Hybrid', pr=3,
 ta='Banking platform engineering', tech='Java/Python/JS, CI/CD, cloud, agile at scale', ex='Final-year students & new grads (GPA ~3.2+)', dg='Bachelor/Master (CS/Eng preferred)', du='2-year structured program, permanent',
 sc=(15,14,8,12,7,10,4,5,3), sa='GBP 56,000-66,000 UK (2023 data); USD 110-125k US', vi='Sponsorship available in many locations (bank-scale)', re='Global firm; relocation possible', po='Annual cycles (UK apps typically open Sep, close ~Nov; US ~Sep-Oct)', dl='Check careers per region', st='Annual - Unverified current window',
 u='https://prosple.com/graduate-employers/jp-morgan/jobs-internships/software-engineer-program', so='JPMorgan SEP official program description (via Prosple)',
 di='Hard', bs='For strong new grads (hackathons/internships help)', ca='Best-in-class structured engineering entry in finance', le='Very high - SDLC, resiliency, security, cloud', cl='Very high',
 rq='GPA; DSA; behavioral prep', sk='Java or Python, DSA, SQL, system basics',
 wy='Global two-year engineering program with top pay and mobility', rk='Extremely competitive; finance pace', rc='HIGH PRIORITY (strong candidates) - applications open Sep-Oct', nt='Code for Good hackathon is a known entry funnel.', il='U', rl='Low'),

dict(c='UK Government - Find an Apprenticeship', ct='Government portal', ti='Level 4 Software Developer Apprenticeships (learn-and-earn)', ot='Apprenticeship', co='UK', ci='England (various)', rm='On-site', pr=3,
 ta='Software development (web/backend)', tech='HTML5/CSS3/JavaScript, testing, CI, GitHub-style version control; C#/Java variants', ex='No experience required (GCSEs English/Maths A*-C desired)', dg='No degree required (Level 4 qualification earned)', du='~18-24 months, employed from day one',
 sc=(15,13,7,11,10,6,3,3,1), sa='Employed wage (examples: GBP 15,600-20,000 first year; many higher)', vi='UK right to work required (no sponsorship)', re='No', po='New vacancies listed weekly on portal', dl='Rolling - each vacancy has own closing date', st='OPEN (portal live; example vacancy VAC2000028362 seen 2026)',
 u='https://www.findapprenticeship.service.gov.uk/apprenticeship/VAC2000028362', so='UK official Find an Apprenticeship service (QA Ltd Level 4 examples)',
 di='Easy-Medium', bs='Perfectly - zero-experience learn-and-earn route', ca='20% off-the-job training + real work; converts to junior dev', le='High - end-to-end dev stack curriculum', cl='Medium',
 rq='UK work eligibility; GCSE Maths/English; weekly vacancy hunting', sk='JS basics, Git, SQL - before interviews',
 wy='Official government learn-and-earn pipeline into software jobs with no degree needed', rk='Wage low first year; UK-only; vacancy quality varies by employer', rc='HIGH PRIORITY (UK work-rights holders) - search "software developer" weekly', nt='Training providers incl. QA Ltd; >18 months standard.', il='N', rl='Low'),

dict(c='FDM Group', ct='IT consultancy (training + placement)', ti='Software Development Graduate Programme (train then place at clients)', ot='Bootcamp-to-Employment (consultancy)', co='UK + global (incl. Frankfurt, KL, Sydney...)', ci='London + global', rm='On-site', pr=3,
 ta='Java/Spring, React consultancy streams', tech='Java, Spring Boot, React, SOLID, design patterns', ex='Graduates any background', dg='Bachelor (any)', du='Weeks of training then 2-year consultant placement at client',
 sc=(13,9,6,10,9,6,3,2,2), sa='GBP 25-30k during training/placement (per candidates); low vs market', vi='Some locations sponsor (check country office)', re='Placement city assigned', po='Rolling intakes', dl='Rolling', st='Open (rolling intakes)',
 u='https://www.glassdoor.com/Reviews/FDM-Group-training-program-Reviews-EI_IE234827.0,9_KH10,26.htm', so='FDM employee reviews (2025-2026) describing training + placement mechanics; official fdmgroup.com',
 di='Easy-Medium', bs='Yes - built for non-IT and fresh grads', ca='Fast structured entry into bank/telecom client teams', le='Medium - solid fundamentals, less modern practice', cl='Low-Medium',
 rq='Degree; mobility for placement; 2-year commitment', sk='Java + SQL basics before training',
 wy='Guaranteed structured training + client placement - a proven foot-in-the-door', rk='2-year bond with training-repayment clause; low pay; placement role may differ from dev; mixed reviews', rc='APPLY IF REQUIREMENTS MET - acceptable fallback, read bond terms carefully', nt='Reddit/Glassdoor: most placements are banks; some report strong perm conversion by clients.', il='U', rl='Medium (bond terms)'),

dict(c='Spotify', ct='Big tech (audio)', ti='Summer Internship (Engineering) - NYC/London/Stockholm', ot='Internship', co='Sweden/UK/US', ci='Stockholm, London, New York', rm='Hybrid (3 days office)', pr=3,
 ta='Audio platform engineering', tech='Backend services, data, ML at scale', ex='Students (UG/MS)', dg='Enrolled; grad year 2026/2027 pattern', du='~10 weeks (mid-Jun to late Aug)',
 sc=(13,13,8,9,6,9,4,5,2), sa='Paid (Spotify intern scale)', vi='Work authorization for country required (no sponsorship for interns)', re='No', po='2026 cycle deadline was 5 Feb 2026', dl='Closed for 2026 - expect Jan-Feb 2027 window', st='Closed (annual)',
 u='https://globalinterndesk.com/spotify-internship-opportunities-2026', so='Spotify 2026 internship listings (multiple boards)',
 di='Hard', bs='For advanced students', ca='Iconic product; strong mentorship culture', le='Very high', cl='Very high',
 rq='Enrolled student; work authorization; DSA', sk='Python/Java/Go, DSA, distributed basics',
 wy='Elite EU/US internship program (annual)', rk='Closed for 2026; location work-rights', rc='GOOD TARGET for 2027 - prepare now', nt='Finance/Research variants exist too.', il='N', rl='Low'),

dict(c='Pipedrive', ct='Scaleup (CRM, Estonia unicorn)', ti='Software Engineering Internship (Tallinn)', ot='Internship', co='Estonia', ci='Tallinn', rm='On-site', pr=3,
 ta='SaaS platform engineering', tech='PHP/JS/React family, Docker, SQL', ex='Fresh grads/final-year/self-taught welcome (per posting text)', dg='No strict requirement - skills-based (HTML/CSS/SQL/React/Docker any)', du='Full-time internship term (summer pattern)',
 sc=(12,13,7,10,9,7,4,3,3), sa='Paid (Estonia intern scale)', vi='Estonia visa possible for non-EU hires (startup-friendly; D-visa routes)', re='Tallinn relocation', po='Past cohort closed ("off the market"); annual pattern', dl='Watch pipedrive.com/careers for next intake', st='Annual - closed for last intake',
 u='https://meetfrank.com/jobs/pipedrive/software-engineering-intern-2', so='Pipedrive SWE internship posting (via MeetFrank)',
 di='Medium', bs='Yes - explicitly targets first-job seekers & self-taught', ca='Estonian unicorn; "learn how software development is done at a real company" framing', le='High - real product teams', cl='Medium',
 rq='Any of HTML/CSS/SQL/React/Docker basics', sk='Web fundamentals + SQL + Git',
 wy='Beginner-welcoming unicorn internship in an e-residency-famous tech country', rk='Annual timing; Tallinn relocation', rc='GOOD TARGET for 2027 intake', nt='Data Science & ML Intern variant also runs.', il='U', rl='Low'),

dict(c='Bolt (EU)', ct='Scaleup (mobility/super-app, Estonia)', ti='Junior Software Engineer (L3 entry level)', ot='Junior Job', co='Estonia', ci='Tallinn', rm='On-site/Hybrid', pr=3,
 ta='Mobility platform engineering', tech='Kotlin/Go/JS backend at scale', ex='Entry level (L3 Junior level exists in ladder)', dg='CS/related', du='Permanent',
 sc=(7,14,6,8,6,7,4,5,3), sa='L3 total comp ~EUR 83k/yr (levels.fyi Estonia sample)', vi='Sponsorship historically possible (Bolt hires internationally)', re='Relocation support cases known', po='Rolling per business need', dl='Check careers', st='Unverified - confirm open junior reqs',
 u='https://www.levels.fyi/companies/bolt-eu/salaries/software-engineer/locations/estonia', so='levels.fyi Bolt Estonia ladder (L3 Junior = entry level)',
 di='Medium-Hard', bs='L3 = true entry level', ca='Fast-scaling EU super-app engineering', le='High', cl='High',
 rq='Strong algorithms; one backend language', sk='Kotlin/Go/Python, SQL, system basics',
 wy='Documented entry-level ladder with strong pay in an English-speaking EU tech hub', rk='Junior reqs appear sporadically; competitive', rc='GOOD TARGET - monitor careers.bolt.eu', nt='', il='U', rl='Low'),

dict(c='Sabre (Krakow)', ct='Global tech (travel software)', ti='Software Engineering Intern 2026 - 6-month program / Summer Internship C++', ot='Internship', co='Poland', ci='Krakow', rm='Hybrid', pr=3,
 ta='Travel industry software', tech='Java, C++, TDD, production troubleshooting', ex='Students/recent grads', dg='BSc CS/IT/Engineering (pursuing or held)', du='6 months (July start) / summer cycles',
 sc=(11,12,7,8,8,7,3,3,3), sa='Poland intern pay (not published)', vi='Poland permits feasible for non-EU students/grads (check)', re='No', po='2026 postings (May-Jun 2026); July 2026 cohort started', dl='Next cycle ~spring 2027', st='Closed for 2026 - annual',
 u='https://builtin.com/job/software-engineering-intern/9472988', so='Built In Sabre Krakow internship listing (2026)',
 di='Medium', bs='Yes', ca='"We would love to see your GitHub" - portfolio-friendly employer', le='High - build/test/demo to Product Owner weekly', cl='Medium',
 rq='Java or C++; TDD awareness; English', sk='Java or C++, Git, testing',
 wy='Big-global-product internship in low-cost EU city, GitHub explicitly welcomed', rk='Annual; Poland relocation', rc='GOOD TARGET for 2027', nt='SW Quality Engineering Intern variant also posted.', il='U', rl='Low'),

dict(c='Nokia (Krakow/Wroclaw)', ct='Global telecom vendor', ti='Software Tester - Summer Trainee', ot='Internship / Trainee', co='Poland', ci='Krakow (also Wroclaw)', rm='Hybrid', pr=3,
 ta='Software testing/QA (telecom)', tech='Test design, automation basics', ex='Active students only', dg='Enrolled degree', du='Summer term',
 sc=(10,10,6,8,8,8,3,3,3), sa='Poland trainee pay', vi='Poland rules for students', re='No', po='2026 cycle closed 3 Jun 2026', dl='Annual ~May 2027', st='Closed (annual)',
 u='https://builtin.com/job/software-tester-summer-trainee-krak-w/8716549', so='Built In Nokia Poland trainee listing (2026)',
 di='Easy-Medium', bs='Yes - student trainee', ca='Global vendor QA entry', le='Medium', cl='Medium',
 rq='Active student status', sk='Python basics, testing concepts',
 wy='Accessible student entry at a global vendor in Poland', rk='QA-flavored (not pure dev); annual', rc='GOOD TARGET (students in Poland)', nt='', il='U', rl='Low'),

dict(c='42 Berlin', ct='Non-profit coding school (industry-funded)', ti='Tuition-free software engineering school (peer-to-peer)', ot='Academy/Training', co='Germany', ci='Berlin', rm='On-site (24/7 campus)', pr=3,
 ta='Software engineering fundamentals', tech='C, C++, Python, web, Unix, group projects', ex='No coding experience required', dg='No degree required (18+)', du='Piscine trial (4 weeks) then core curriculum (self-paced ~1-3 yrs)',
 sc=(14,13,6,8,10,6,4,3,3), sa='Free tuition (VW/SAP/Microsoft funded); no salary', vi='German visa route possible for non-EU (check; school is not a visa sponsor)', re='Berlin living costs self-funded', po='Rolling Piscine intakes', dl='Rolling', st='Open (rolling)',
 u='https://www.42berlin.de/letscodethefuture', so='42 Berlin official site',
 di='Hard (self-driven intensity)', bs='Yes - zero-experience accepted', ca='Elite-recognized pedagogy; Berlin tech scene access; high graduate employment reputation', le='Very high - learn by building with peers', cl='Medium',
 rq='Logical game + Piscine pass; full-time presence; funding for living', sk='C fundamentals via Piscine',
 wy='Free, respected, project-based route into the Berlin job market', rk='No salary during study; German housing; self-direction required', rc='GOOD TARGET for committed career-changers targeting Germany', nt='', il='U', rl='Low'),
]
